// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/client/audit_data_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/enterprise_config_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/enterprise_frontend_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/enterprise_log_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/enterprise_policy_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/enterprise_templates_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/enterprise_token_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/license_service"
	"github.com/pydio/cells-enterprise-sdk-go/client/scheduler_service"
)

// Default pydio cells enterprise rest API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https", "wss"}

// NewHTTPClient creates a new pydio cells enterprise rest API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *PydioCellsEnterpriseRestAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new pydio cells enterprise rest API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *PydioCellsEnterpriseRestAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new pydio cells enterprise rest API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *PydioCellsEnterpriseRestAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(PydioCellsEnterpriseRestAPI)
	cli.Transport = transport
	cli.AuditDataService = audit_data_service.New(transport, formats)
	cli.EnterpriseConfigService = enterprise_config_service.New(transport, formats)
	cli.EnterpriseFrontendService = enterprise_frontend_service.New(transport, formats)
	cli.EnterpriseLogService = enterprise_log_service.New(transport, formats)
	cli.EnterprisePolicyService = enterprise_policy_service.New(transport, formats)
	cli.EnterpriseTemplatesService = enterprise_templates_service.New(transport, formats)
	cli.EnterpriseTokenService = enterprise_token_service.New(transport, formats)
	cli.LicenseService = license_service.New(transport, formats)
	cli.SchedulerService = scheduler_service.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// PydioCellsEnterpriseRestAPI is a client for pydio cells enterprise rest API
type PydioCellsEnterpriseRestAPI struct {
	AuditDataService audit_data_service.ClientService

	EnterpriseConfigService enterprise_config_service.ClientService

	EnterpriseFrontendService enterprise_frontend_service.ClientService

	EnterpriseLogService enterprise_log_service.ClientService

	EnterprisePolicyService enterprise_policy_service.ClientService

	EnterpriseTemplatesService enterprise_templates_service.ClientService

	EnterpriseTokenService enterprise_token_service.ClientService

	LicenseService license_service.ClientService

	SchedulerService scheduler_service.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *PydioCellsEnterpriseRestAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.AuditDataService.SetTransport(transport)
	c.EnterpriseConfigService.SetTransport(transport)
	c.EnterpriseFrontendService.SetTransport(transport)
	c.EnterpriseLogService.SetTransport(transport)
	c.EnterprisePolicyService.SetTransport(transport)
	c.EnterpriseTemplatesService.SetTransport(transport)
	c.EnterpriseTokenService.SetTransport(transport)
	c.LicenseService.SetTransport(transport)
	c.SchedulerService.SetTransport(transport)
}
