// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteActionTemplateReader is a Reader for the DeleteActionTemplate structure.
type DeleteActionTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteActionTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteActionTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteActionTemplateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteActionTemplateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteActionTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteActionTemplateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteActionTemplateOK creates a DeleteActionTemplateOK with default headers values
func NewDeleteActionTemplateOK() *DeleteActionTemplateOK {
	return &DeleteActionTemplateOK{}
}

/* DeleteActionTemplateOK describes a response with status code 200, with default header values.

DeleteActionTemplateOK delete action template o k
*/
type DeleteActionTemplateOK struct {
	Payload *models.EntDeleteActionTemplateResponse
}

func (o *DeleteActionTemplateOK) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] deleteActionTemplateOK  %+v", 200, o.Payload)
}
func (o *DeleteActionTemplateOK) GetPayload() *models.EntDeleteActionTemplateResponse {
	return o.Payload
}

func (o *DeleteActionTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntDeleteActionTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteActionTemplateUnauthorized creates a DeleteActionTemplateUnauthorized with default headers values
func NewDeleteActionTemplateUnauthorized() *DeleteActionTemplateUnauthorized {
	return &DeleteActionTemplateUnauthorized{}
}

/* DeleteActionTemplateUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type DeleteActionTemplateUnauthorized struct {
}

func (o *DeleteActionTemplateUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] deleteActionTemplateUnauthorized ", 401)
}

func (o *DeleteActionTemplateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteActionTemplateForbidden creates a DeleteActionTemplateForbidden with default headers values
func NewDeleteActionTemplateForbidden() *DeleteActionTemplateForbidden {
	return &DeleteActionTemplateForbidden{}
}

/* DeleteActionTemplateForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type DeleteActionTemplateForbidden struct {
	Payload *models.RestError
}

func (o *DeleteActionTemplateForbidden) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] deleteActionTemplateForbidden  %+v", 403, o.Payload)
}
func (o *DeleteActionTemplateForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteActionTemplateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteActionTemplateNotFound creates a DeleteActionTemplateNotFound with default headers values
func NewDeleteActionTemplateNotFound() *DeleteActionTemplateNotFound {
	return &DeleteActionTemplateNotFound{}
}

/* DeleteActionTemplateNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type DeleteActionTemplateNotFound struct {
	Payload *models.RestError
}

func (o *DeleteActionTemplateNotFound) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] deleteActionTemplateNotFound  %+v", 404, o.Payload)
}
func (o *DeleteActionTemplateNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteActionTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteActionTemplateInternalServerError creates a DeleteActionTemplateInternalServerError with default headers values
func NewDeleteActionTemplateInternalServerError() *DeleteActionTemplateInternalServerError {
	return &DeleteActionTemplateInternalServerError{}
}

/* DeleteActionTemplateInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type DeleteActionTemplateInternalServerError struct {
	Payload *models.RestError
}

func (o *DeleteActionTemplateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] deleteActionTemplateInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteActionTemplateInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteActionTemplateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
