// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSelectorTemplateParams creates a new DeleteSelectorTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSelectorTemplateParams() *DeleteSelectorTemplateParams {
	return &DeleteSelectorTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSelectorTemplateParamsWithTimeout creates a new DeleteSelectorTemplateParams object
// with the ability to set a timeout on a request.
func NewDeleteSelectorTemplateParamsWithTimeout(timeout time.Duration) *DeleteSelectorTemplateParams {
	return &DeleteSelectorTemplateParams{
		timeout: timeout,
	}
}

// NewDeleteSelectorTemplateParamsWithContext creates a new DeleteSelectorTemplateParams object
// with the ability to set a context for a request.
func NewDeleteSelectorTemplateParamsWithContext(ctx context.Context) *DeleteSelectorTemplateParams {
	return &DeleteSelectorTemplateParams{
		Context: ctx,
	}
}

// NewDeleteSelectorTemplateParamsWithHTTPClient creates a new DeleteSelectorTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSelectorTemplateParamsWithHTTPClient(client *http.Client) *DeleteSelectorTemplateParams {
	return &DeleteSelectorTemplateParams{
		HTTPClient: client,
	}
}

/* DeleteSelectorTemplateParams contains all the parameters to send to the API endpoint
   for the delete selector template operation.

   Typically these are written to a http.Request.
*/
type DeleteSelectorTemplateParams struct {

	// TemplateName.
	TemplateName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete selector template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSelectorTemplateParams) WithDefaults() *DeleteSelectorTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete selector template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSelectorTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete selector template params
func (o *DeleteSelectorTemplateParams) WithTimeout(timeout time.Duration) *DeleteSelectorTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete selector template params
func (o *DeleteSelectorTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete selector template params
func (o *DeleteSelectorTemplateParams) WithContext(ctx context.Context) *DeleteSelectorTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete selector template params
func (o *DeleteSelectorTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete selector template params
func (o *DeleteSelectorTemplateParams) WithHTTPClient(client *http.Client) *DeleteSelectorTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete selector template params
func (o *DeleteSelectorTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTemplateName adds the templateName to the delete selector template params
func (o *DeleteSelectorTemplateParams) WithTemplateName(templateName string) *DeleteSelectorTemplateParams {
	o.SetTemplateName(templateName)
	return o
}

// SetTemplateName adds the templateName to the delete selector template params
func (o *DeleteSelectorTemplateParams) SetTemplateName(templateName string) {
	o.TemplateName = templateName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSelectorTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param TemplateName
	if err := r.SetPathParam("TemplateName", o.TemplateName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
