// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteJobReader is a Reader for the DeleteJob structure.
type DeleteJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteJobForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteJobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteJobOK creates a DeleteJobOK with default headers values
func NewDeleteJobOK() *DeleteJobOK {
	return &DeleteJobOK{}
}

/* DeleteJobOK describes a response with status code 200, with default header values.

DeleteJobOK delete job o k
*/
type DeleteJobOK struct {
	Payload *models.JobsDeleteJobResponse
}

func (o *DeleteJobOK) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/jobs/{JobID}][%d] deleteJobOK  %+v", 200, o.Payload)
}
func (o *DeleteJobOK) GetPayload() *models.JobsDeleteJobResponse {
	return o.Payload
}

func (o *DeleteJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobsDeleteJobResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobUnauthorized creates a DeleteJobUnauthorized with default headers values
func NewDeleteJobUnauthorized() *DeleteJobUnauthorized {
	return &DeleteJobUnauthorized{}
}

/* DeleteJobUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type DeleteJobUnauthorized struct {
}

func (o *DeleteJobUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/jobs/{JobID}][%d] deleteJobUnauthorized ", 401)
}

func (o *DeleteJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobForbidden creates a DeleteJobForbidden with default headers values
func NewDeleteJobForbidden() *DeleteJobForbidden {
	return &DeleteJobForbidden{}
}

/* DeleteJobForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type DeleteJobForbidden struct {
	Payload *models.RestError
}

func (o *DeleteJobForbidden) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/jobs/{JobID}][%d] deleteJobForbidden  %+v", 403, o.Payload)
}
func (o *DeleteJobForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobNotFound creates a DeleteJobNotFound with default headers values
func NewDeleteJobNotFound() *DeleteJobNotFound {
	return &DeleteJobNotFound{}
}

/* DeleteJobNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type DeleteJobNotFound struct {
	Payload *models.RestError
}

func (o *DeleteJobNotFound) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/jobs/{JobID}][%d] deleteJobNotFound  %+v", 404, o.Payload)
}
func (o *DeleteJobNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobInternalServerError creates a DeleteJobInternalServerError with default headers values
func NewDeleteJobInternalServerError() *DeleteJobInternalServerError {
	return &DeleteJobInternalServerError{}
}

/* DeleteJobInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type DeleteJobInternalServerError struct {
	Payload *models.RestError
}

func (o *DeleteJobInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/jobs/{JobID}][%d] deleteJobInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteJobInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
