// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteSelectorTemplateReader is a Reader for the DeleteSelectorTemplate structure.
type DeleteSelectorTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSelectorTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSelectorTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteSelectorTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSelectorTemplateOK creates a DeleteSelectorTemplateOK with default headers values
func NewDeleteSelectorTemplateOK() *DeleteSelectorTemplateOK {
	return &DeleteSelectorTemplateOK{}
}

/*
DeleteSelectorTemplateOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteSelectorTemplateOK struct {
	Payload *models.EntDeleteSelectorTemplateResponse
}

// IsSuccess returns true when this delete selector template o k response has a 2xx status code
func (o *DeleteSelectorTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete selector template o k response has a 3xx status code
func (o *DeleteSelectorTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete selector template o k response has a 4xx status code
func (o *DeleteSelectorTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete selector template o k response has a 5xx status code
func (o *DeleteSelectorTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete selector template o k response a status code equal to that given
func (o *DeleteSelectorTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete selector template o k response
func (o *DeleteSelectorTemplateOK) Code() int {
	return 200
}

func (o *DeleteSelectorTemplateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/selectors/{TemplateName}][%d] deleteSelectorTemplateOK %s", 200, payload)
}

func (o *DeleteSelectorTemplateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/selectors/{TemplateName}][%d] deleteSelectorTemplateOK %s", 200, payload)
}

func (o *DeleteSelectorTemplateOK) GetPayload() *models.EntDeleteSelectorTemplateResponse {
	return o.Payload
}

func (o *DeleteSelectorTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntDeleteSelectorTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSelectorTemplateDefault creates a DeleteSelectorTemplateDefault with default headers values
func NewDeleteSelectorTemplateDefault(code int) *DeleteSelectorTemplateDefault {
	return &DeleteSelectorTemplateDefault{
		_statusCode: code,
	}
}

/*
DeleteSelectorTemplateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteSelectorTemplateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this delete selector template default response has a 2xx status code
func (o *DeleteSelectorTemplateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete selector template default response has a 3xx status code
func (o *DeleteSelectorTemplateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete selector template default response has a 4xx status code
func (o *DeleteSelectorTemplateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete selector template default response has a 5xx status code
func (o *DeleteSelectorTemplateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete selector template default response a status code equal to that given
func (o *DeleteSelectorTemplateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete selector template default response
func (o *DeleteSelectorTemplateDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSelectorTemplateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/selectors/{TemplateName}][%d] DeleteSelectorTemplate default %s", o._statusCode, payload)
}

func (o *DeleteSelectorTemplateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/selectors/{TemplateName}][%d] DeleteSelectorTemplate default %s", o._statusCode, payload)
}

func (o *DeleteSelectorTemplateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *DeleteSelectorTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
