// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteActionTemplateParams creates a new DeleteActionTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteActionTemplateParams() *DeleteActionTemplateParams {
	return &DeleteActionTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteActionTemplateParamsWithTimeout creates a new DeleteActionTemplateParams object
// with the ability to set a timeout on a request.
func NewDeleteActionTemplateParamsWithTimeout(timeout time.Duration) *DeleteActionTemplateParams {
	return &DeleteActionTemplateParams{
		timeout: timeout,
	}
}

// NewDeleteActionTemplateParamsWithContext creates a new DeleteActionTemplateParams object
// with the ability to set a context for a request.
func NewDeleteActionTemplateParamsWithContext(ctx context.Context) *DeleteActionTemplateParams {
	return &DeleteActionTemplateParams{
		Context: ctx,
	}
}

// NewDeleteActionTemplateParamsWithHTTPClient creates a new DeleteActionTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteActionTemplateParamsWithHTTPClient(client *http.Client) *DeleteActionTemplateParams {
	return &DeleteActionTemplateParams{
		HTTPClient: client,
	}
}

/* DeleteActionTemplateParams contains all the parameters to send to the API endpoint
   for the delete action template operation.

   Typically these are written to a http.Request.
*/
type DeleteActionTemplateParams struct {

	// TemplateName.
	TemplateName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete action template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteActionTemplateParams) WithDefaults() *DeleteActionTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete action template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteActionTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete action template params
func (o *DeleteActionTemplateParams) WithTimeout(timeout time.Duration) *DeleteActionTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete action template params
func (o *DeleteActionTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete action template params
func (o *DeleteActionTemplateParams) WithContext(ctx context.Context) *DeleteActionTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete action template params
func (o *DeleteActionTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete action template params
func (o *DeleteActionTemplateParams) WithHTTPClient(client *http.Client) *DeleteActionTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete action template params
func (o *DeleteActionTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTemplateName adds the templateName to the delete action template params
func (o *DeleteActionTemplateParams) WithTemplateName(templateName string) *DeleteActionTemplateParams {
	o.SetTemplateName(templateName)
	return o
}

// SetTemplateName adds the templateName to the delete action template params
func (o *DeleteActionTemplateParams) SetTemplateName(templateName string) {
	o.TemplateName = templateName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteActionTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param TemplateName
	if err := r.SetPathParam("TemplateName", o.TemplateName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
