// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteJobTemplateReader is a Reader for the DeleteJobTemplate structure.
type DeleteJobTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteJobTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteJobTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteJobTemplateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteJobTemplateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteJobTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteJobTemplateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteJobTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteJobTemplateOK creates a DeleteJobTemplateOK with default headers values
func NewDeleteJobTemplateOK() *DeleteJobTemplateOK {
	return &DeleteJobTemplateOK{}
}

/*
DeleteJobTemplateOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteJobTemplateOK struct {
	Payload *models.EntDeleteJobTemplateResponse
}

// IsSuccess returns true when this delete job template o k response has a 2xx status code
func (o *DeleteJobTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete job template o k response has a 3xx status code
func (o *DeleteJobTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job template o k response has a 4xx status code
func (o *DeleteJobTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete job template o k response has a 5xx status code
func (o *DeleteJobTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job template o k response a status code equal to that given
func (o *DeleteJobTemplateOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteJobTemplateOK) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateOK  %+v", 200, o.Payload)
}

func (o *DeleteJobTemplateOK) String() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateOK  %+v", 200, o.Payload)
}

func (o *DeleteJobTemplateOK) GetPayload() *models.EntDeleteJobTemplateResponse {
	return o.Payload
}

func (o *DeleteJobTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntDeleteJobTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobTemplateUnauthorized creates a DeleteJobTemplateUnauthorized with default headers values
func NewDeleteJobTemplateUnauthorized() *DeleteJobTemplateUnauthorized {
	return &DeleteJobTemplateUnauthorized{}
}

/*
DeleteJobTemplateUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type DeleteJobTemplateUnauthorized struct {
}

// IsSuccess returns true when this delete job template unauthorized response has a 2xx status code
func (o *DeleteJobTemplateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job template unauthorized response has a 3xx status code
func (o *DeleteJobTemplateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job template unauthorized response has a 4xx status code
func (o *DeleteJobTemplateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete job template unauthorized response has a 5xx status code
func (o *DeleteJobTemplateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job template unauthorized response a status code equal to that given
func (o *DeleteJobTemplateUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *DeleteJobTemplateUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateUnauthorized ", 401)
}

func (o *DeleteJobTemplateUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateUnauthorized ", 401)
}

func (o *DeleteJobTemplateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobTemplateForbidden creates a DeleteJobTemplateForbidden with default headers values
func NewDeleteJobTemplateForbidden() *DeleteJobTemplateForbidden {
	return &DeleteJobTemplateForbidden{}
}

/*
DeleteJobTemplateForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type DeleteJobTemplateForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this delete job template forbidden response has a 2xx status code
func (o *DeleteJobTemplateForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job template forbidden response has a 3xx status code
func (o *DeleteJobTemplateForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job template forbidden response has a 4xx status code
func (o *DeleteJobTemplateForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete job template forbidden response has a 5xx status code
func (o *DeleteJobTemplateForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job template forbidden response a status code equal to that given
func (o *DeleteJobTemplateForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *DeleteJobTemplateForbidden) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateForbidden  %+v", 403, o.Payload)
}

func (o *DeleteJobTemplateForbidden) String() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateForbidden  %+v", 403, o.Payload)
}

func (o *DeleteJobTemplateForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobTemplateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobTemplateNotFound creates a DeleteJobTemplateNotFound with default headers values
func NewDeleteJobTemplateNotFound() *DeleteJobTemplateNotFound {
	return &DeleteJobTemplateNotFound{}
}

/*
DeleteJobTemplateNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type DeleteJobTemplateNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this delete job template not found response has a 2xx status code
func (o *DeleteJobTemplateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job template not found response has a 3xx status code
func (o *DeleteJobTemplateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job template not found response has a 4xx status code
func (o *DeleteJobTemplateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete job template not found response has a 5xx status code
func (o *DeleteJobTemplateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job template not found response a status code equal to that given
func (o *DeleteJobTemplateNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteJobTemplateNotFound) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateNotFound  %+v", 404, o.Payload)
}

func (o *DeleteJobTemplateNotFound) String() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateNotFound  %+v", 404, o.Payload)
}

func (o *DeleteJobTemplateNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobTemplateInternalServerError creates a DeleteJobTemplateInternalServerError with default headers values
func NewDeleteJobTemplateInternalServerError() *DeleteJobTemplateInternalServerError {
	return &DeleteJobTemplateInternalServerError{}
}

/*
DeleteJobTemplateInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type DeleteJobTemplateInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this delete job template internal server error response has a 2xx status code
func (o *DeleteJobTemplateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job template internal server error response has a 3xx status code
func (o *DeleteJobTemplateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job template internal server error response has a 4xx status code
func (o *DeleteJobTemplateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete job template internal server error response has a 5xx status code
func (o *DeleteJobTemplateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete job template internal server error response a status code equal to that given
func (o *DeleteJobTemplateInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeleteJobTemplateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteJobTemplateInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteJobTemplateInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobTemplateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobTemplateDefault creates a DeleteJobTemplateDefault with default headers values
func NewDeleteJobTemplateDefault(code int) *DeleteJobTemplateDefault {
	return &DeleteJobTemplateDefault{
		_statusCode: code,
	}
}

/*
DeleteJobTemplateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteJobTemplateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the delete job template default response
func (o *DeleteJobTemplateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete job template default response has a 2xx status code
func (o *DeleteJobTemplateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete job template default response has a 3xx status code
func (o *DeleteJobTemplateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete job template default response has a 4xx status code
func (o *DeleteJobTemplateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete job template default response has a 5xx status code
func (o *DeleteJobTemplateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete job template default response a status code equal to that given
func (o *DeleteJobTemplateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteJobTemplateDefault) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] DeleteJobTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteJobTemplateDefault) String() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] DeleteJobTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteJobTemplateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *DeleteJobTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
