// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteJobTemplateReader is a Reader for the DeleteJobTemplate structure.
type DeleteJobTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteJobTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteJobTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteJobTemplateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteJobTemplateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteJobTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteJobTemplateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteJobTemplateOK creates a DeleteJobTemplateOK with default headers values
func NewDeleteJobTemplateOK() *DeleteJobTemplateOK {
	return &DeleteJobTemplateOK{}
}

/* DeleteJobTemplateOK describes a response with status code 200, with default header values.

DeleteJobTemplateOK delete job template o k
*/
type DeleteJobTemplateOK struct {
	Payload *models.EntDeleteJobTemplateResponse
}

func (o *DeleteJobTemplateOK) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateOK  %+v", 200, o.Payload)
}
func (o *DeleteJobTemplateOK) GetPayload() *models.EntDeleteJobTemplateResponse {
	return o.Payload
}

func (o *DeleteJobTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntDeleteJobTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobTemplateUnauthorized creates a DeleteJobTemplateUnauthorized with default headers values
func NewDeleteJobTemplateUnauthorized() *DeleteJobTemplateUnauthorized {
	return &DeleteJobTemplateUnauthorized{}
}

/* DeleteJobTemplateUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type DeleteJobTemplateUnauthorized struct {
}

func (o *DeleteJobTemplateUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateUnauthorized ", 401)
}

func (o *DeleteJobTemplateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobTemplateForbidden creates a DeleteJobTemplateForbidden with default headers values
func NewDeleteJobTemplateForbidden() *DeleteJobTemplateForbidden {
	return &DeleteJobTemplateForbidden{}
}

/* DeleteJobTemplateForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type DeleteJobTemplateForbidden struct {
	Payload *models.RestError
}

func (o *DeleteJobTemplateForbidden) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateForbidden  %+v", 403, o.Payload)
}
func (o *DeleteJobTemplateForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobTemplateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobTemplateNotFound creates a DeleteJobTemplateNotFound with default headers values
func NewDeleteJobTemplateNotFound() *DeleteJobTemplateNotFound {
	return &DeleteJobTemplateNotFound{}
}

/* DeleteJobTemplateNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type DeleteJobTemplateNotFound struct {
	Payload *models.RestError
}

func (o *DeleteJobTemplateNotFound) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateNotFound  %+v", 404, o.Payload)
}
func (o *DeleteJobTemplateNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobTemplateInternalServerError creates a DeleteJobTemplateInternalServerError with default headers values
func NewDeleteJobTemplateInternalServerError() *DeleteJobTemplateInternalServerError {
	return &DeleteJobTemplateInternalServerError{}
}

/* DeleteJobTemplateInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type DeleteJobTemplateInternalServerError struct {
	Payload *models.RestError
}

func (o *DeleteJobTemplateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/templates/jobs/{Name}][%d] deleteJobTemplateInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteJobTemplateInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobTemplateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
