// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteActionTemplateReader is a Reader for the DeleteActionTemplate structure.
type DeleteActionTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteActionTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteActionTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteActionTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteActionTemplateOK creates a DeleteActionTemplateOK with default headers values
func NewDeleteActionTemplateOK() *DeleteActionTemplateOK {
	return &DeleteActionTemplateOK{}
}

/*
DeleteActionTemplateOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteActionTemplateOK struct {
	Payload *models.EntDeleteActionTemplateResponse
}

// IsSuccess returns true when this delete action template o k response has a 2xx status code
func (o *DeleteActionTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete action template o k response has a 3xx status code
func (o *DeleteActionTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete action template o k response has a 4xx status code
func (o *DeleteActionTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete action template o k response has a 5xx status code
func (o *DeleteActionTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete action template o k response a status code equal to that given
func (o *DeleteActionTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete action template o k response
func (o *DeleteActionTemplateOK) Code() int {
	return 200
}

func (o *DeleteActionTemplateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] deleteActionTemplateOK %s", 200, payload)
}

func (o *DeleteActionTemplateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] deleteActionTemplateOK %s", 200, payload)
}

func (o *DeleteActionTemplateOK) GetPayload() *models.EntDeleteActionTemplateResponse {
	return o.Payload
}

func (o *DeleteActionTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntDeleteActionTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteActionTemplateDefault creates a DeleteActionTemplateDefault with default headers values
func NewDeleteActionTemplateDefault(code int) *DeleteActionTemplateDefault {
	return &DeleteActionTemplateDefault{
		_statusCode: code,
	}
}

/*
DeleteActionTemplateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteActionTemplateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this delete action template default response has a 2xx status code
func (o *DeleteActionTemplateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete action template default response has a 3xx status code
func (o *DeleteActionTemplateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete action template default response has a 4xx status code
func (o *DeleteActionTemplateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete action template default response has a 5xx status code
func (o *DeleteActionTemplateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete action template default response a status code equal to that given
func (o *DeleteActionTemplateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete action template default response
func (o *DeleteActionTemplateDefault) Code() int {
	return o._statusCode
}

func (o *DeleteActionTemplateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] DeleteActionTemplate default %s", o._statusCode, payload)
}

func (o *DeleteActionTemplateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /scheduler/templates/actions/{TemplateName}][%d] DeleteActionTemplate default %s", o._statusCode, payload)
}

func (o *DeleteActionTemplateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *DeleteActionTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
