// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteJobVersionReader is a Reader for the DeleteJobVersion structure.
type DeleteJobVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteJobVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteJobVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteJobVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteJobVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteJobVersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteJobVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteJobVersionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteJobVersionOK creates a DeleteJobVersionOK with default headers values
func NewDeleteJobVersionOK() *DeleteJobVersionOK {
	return &DeleteJobVersionOK{}
}

/*
DeleteJobVersionOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteJobVersionOK struct {
	Payload *models.EntDeleteJobVersionResponse
}

// IsSuccess returns true when this delete job version o k response has a 2xx status code
func (o *DeleteJobVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete job version o k response has a 3xx status code
func (o *DeleteJobVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job version o k response has a 4xx status code
func (o *DeleteJobVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete job version o k response has a 5xx status code
func (o *DeleteJobVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job version o k response a status code equal to that given
func (o *DeleteJobVersionOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteJobVersionOK) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionOK  %+v", 200, o.Payload)
}

func (o *DeleteJobVersionOK) String() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionOK  %+v", 200, o.Payload)
}

func (o *DeleteJobVersionOK) GetPayload() *models.EntDeleteJobVersionResponse {
	return o.Payload
}

func (o *DeleteJobVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntDeleteJobVersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobVersionUnauthorized creates a DeleteJobVersionUnauthorized with default headers values
func NewDeleteJobVersionUnauthorized() *DeleteJobVersionUnauthorized {
	return &DeleteJobVersionUnauthorized{}
}

/*
DeleteJobVersionUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type DeleteJobVersionUnauthorized struct {
}

// IsSuccess returns true when this delete job version unauthorized response has a 2xx status code
func (o *DeleteJobVersionUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job version unauthorized response has a 3xx status code
func (o *DeleteJobVersionUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job version unauthorized response has a 4xx status code
func (o *DeleteJobVersionUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete job version unauthorized response has a 5xx status code
func (o *DeleteJobVersionUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job version unauthorized response a status code equal to that given
func (o *DeleteJobVersionUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *DeleteJobVersionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionUnauthorized ", 401)
}

func (o *DeleteJobVersionUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionUnauthorized ", 401)
}

func (o *DeleteJobVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobVersionForbidden creates a DeleteJobVersionForbidden with default headers values
func NewDeleteJobVersionForbidden() *DeleteJobVersionForbidden {
	return &DeleteJobVersionForbidden{}
}

/*
DeleteJobVersionForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type DeleteJobVersionForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this delete job version forbidden response has a 2xx status code
func (o *DeleteJobVersionForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job version forbidden response has a 3xx status code
func (o *DeleteJobVersionForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job version forbidden response has a 4xx status code
func (o *DeleteJobVersionForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete job version forbidden response has a 5xx status code
func (o *DeleteJobVersionForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job version forbidden response a status code equal to that given
func (o *DeleteJobVersionForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *DeleteJobVersionForbidden) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionForbidden  %+v", 403, o.Payload)
}

func (o *DeleteJobVersionForbidden) String() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionForbidden  %+v", 403, o.Payload)
}

func (o *DeleteJobVersionForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobVersionNotFound creates a DeleteJobVersionNotFound with default headers values
func NewDeleteJobVersionNotFound() *DeleteJobVersionNotFound {
	return &DeleteJobVersionNotFound{}
}

/*
DeleteJobVersionNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type DeleteJobVersionNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this delete job version not found response has a 2xx status code
func (o *DeleteJobVersionNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job version not found response has a 3xx status code
func (o *DeleteJobVersionNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job version not found response has a 4xx status code
func (o *DeleteJobVersionNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete job version not found response has a 5xx status code
func (o *DeleteJobVersionNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete job version not found response a status code equal to that given
func (o *DeleteJobVersionNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteJobVersionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionNotFound  %+v", 404, o.Payload)
}

func (o *DeleteJobVersionNotFound) String() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionNotFound  %+v", 404, o.Payload)
}

func (o *DeleteJobVersionNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobVersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobVersionInternalServerError creates a DeleteJobVersionInternalServerError with default headers values
func NewDeleteJobVersionInternalServerError() *DeleteJobVersionInternalServerError {
	return &DeleteJobVersionInternalServerError{}
}

/*
DeleteJobVersionInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type DeleteJobVersionInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this delete job version internal server error response has a 2xx status code
func (o *DeleteJobVersionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete job version internal server error response has a 3xx status code
func (o *DeleteJobVersionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete job version internal server error response has a 4xx status code
func (o *DeleteJobVersionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete job version internal server error response has a 5xx status code
func (o *DeleteJobVersionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete job version internal server error response a status code equal to that given
func (o *DeleteJobVersionInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeleteJobVersionInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteJobVersionInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] deleteJobVersionInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteJobVersionInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteJobVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobVersionDefault creates a DeleteJobVersionDefault with default headers values
func NewDeleteJobVersionDefault(code int) *DeleteJobVersionDefault {
	return &DeleteJobVersionDefault{
		_statusCode: code,
	}
}

/*
DeleteJobVersionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteJobVersionDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the delete job version default response
func (o *DeleteJobVersionDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete job version default response has a 2xx status code
func (o *DeleteJobVersionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete job version default response has a 3xx status code
func (o *DeleteJobVersionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete job version default response has a 4xx status code
func (o *DeleteJobVersionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete job version default response has a 5xx status code
func (o *DeleteJobVersionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete job version default response a status code equal to that given
func (o *DeleteJobVersionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteJobVersionDefault) Error() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] DeleteJobVersion default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteJobVersionDefault) String() string {
	return fmt.Sprintf("[DELETE /scheduler/versions/{JobID}/{VersionID}][%d] DeleteJobVersion default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteJobVersionDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *DeleteJobVersionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
