// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// NewExecutePlaygroundCodeParams creates a new ExecutePlaygroundCodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExecutePlaygroundCodeParams() *ExecutePlaygroundCodeParams {
	return &ExecutePlaygroundCodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExecutePlaygroundCodeParamsWithTimeout creates a new ExecutePlaygroundCodeParams object
// with the ability to set a timeout on a request.
func NewExecutePlaygroundCodeParamsWithTimeout(timeout time.Duration) *ExecutePlaygroundCodeParams {
	return &ExecutePlaygroundCodeParams{
		timeout: timeout,
	}
}

// NewExecutePlaygroundCodeParamsWithContext creates a new ExecutePlaygroundCodeParams object
// with the ability to set a context for a request.
func NewExecutePlaygroundCodeParamsWithContext(ctx context.Context) *ExecutePlaygroundCodeParams {
	return &ExecutePlaygroundCodeParams{
		Context: ctx,
	}
}

// NewExecutePlaygroundCodeParamsWithHTTPClient creates a new ExecutePlaygroundCodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewExecutePlaygroundCodeParamsWithHTTPClient(client *http.Client) *ExecutePlaygroundCodeParams {
	return &ExecutePlaygroundCodeParams{
		HTTPClient: client,
	}
}

/*
ExecutePlaygroundCodeParams contains all the parameters to send to the API endpoint

	for the execute playground code operation.

	Typically these are written to a http.Request.
*/
type ExecutePlaygroundCodeParams struct {

	// Body.
	Body *models.EntPlaygroundRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the execute playground code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExecutePlaygroundCodeParams) WithDefaults() *ExecutePlaygroundCodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the execute playground code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExecutePlaygroundCodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the execute playground code params
func (o *ExecutePlaygroundCodeParams) WithTimeout(timeout time.Duration) *ExecutePlaygroundCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the execute playground code params
func (o *ExecutePlaygroundCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the execute playground code params
func (o *ExecutePlaygroundCodeParams) WithContext(ctx context.Context) *ExecutePlaygroundCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the execute playground code params
func (o *ExecutePlaygroundCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the execute playground code params
func (o *ExecutePlaygroundCodeParams) WithHTTPClient(client *http.Client) *ExecutePlaygroundCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the execute playground code params
func (o *ExecutePlaygroundCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the execute playground code params
func (o *ExecutePlaygroundCodeParams) WithBody(body *models.EntPlaygroundRequest) *ExecutePlaygroundCodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the execute playground code params
func (o *ExecutePlaygroundCodeParams) SetBody(body *models.EntPlaygroundRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ExecutePlaygroundCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
