// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// ListSelectorTemplatesReader is a Reader for the ListSelectorTemplates structure.
type ListSelectorTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSelectorTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSelectorTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListSelectorTemplatesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListSelectorTemplatesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListSelectorTemplatesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListSelectorTemplatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListSelectorTemplatesOK creates a ListSelectorTemplatesOK with default headers values
func NewListSelectorTemplatesOK() *ListSelectorTemplatesOK {
	return &ListSelectorTemplatesOK{}
}

/* ListSelectorTemplatesOK describes a response with status code 200, with default header values.

ListSelectorTemplatesOK list selector templates o k
*/
type ListSelectorTemplatesOK struct {
	Payload *models.EntListSelectorTemplatesResponse
}

func (o *ListSelectorTemplatesOK) Error() string {
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] listSelectorTemplatesOK  %+v", 200, o.Payload)
}
func (o *ListSelectorTemplatesOK) GetPayload() *models.EntListSelectorTemplatesResponse {
	return o.Payload
}

func (o *ListSelectorTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntListSelectorTemplatesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSelectorTemplatesUnauthorized creates a ListSelectorTemplatesUnauthorized with default headers values
func NewListSelectorTemplatesUnauthorized() *ListSelectorTemplatesUnauthorized {
	return &ListSelectorTemplatesUnauthorized{}
}

/* ListSelectorTemplatesUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type ListSelectorTemplatesUnauthorized struct {
}

func (o *ListSelectorTemplatesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] listSelectorTemplatesUnauthorized ", 401)
}

func (o *ListSelectorTemplatesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListSelectorTemplatesForbidden creates a ListSelectorTemplatesForbidden with default headers values
func NewListSelectorTemplatesForbidden() *ListSelectorTemplatesForbidden {
	return &ListSelectorTemplatesForbidden{}
}

/* ListSelectorTemplatesForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type ListSelectorTemplatesForbidden struct {
	Payload *models.RestError
}

func (o *ListSelectorTemplatesForbidden) Error() string {
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] listSelectorTemplatesForbidden  %+v", 403, o.Payload)
}
func (o *ListSelectorTemplatesForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListSelectorTemplatesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSelectorTemplatesNotFound creates a ListSelectorTemplatesNotFound with default headers values
func NewListSelectorTemplatesNotFound() *ListSelectorTemplatesNotFound {
	return &ListSelectorTemplatesNotFound{}
}

/* ListSelectorTemplatesNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type ListSelectorTemplatesNotFound struct {
	Payload *models.RestError
}

func (o *ListSelectorTemplatesNotFound) Error() string {
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] listSelectorTemplatesNotFound  %+v", 404, o.Payload)
}
func (o *ListSelectorTemplatesNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListSelectorTemplatesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSelectorTemplatesInternalServerError creates a ListSelectorTemplatesInternalServerError with default headers values
func NewListSelectorTemplatesInternalServerError() *ListSelectorTemplatesInternalServerError {
	return &ListSelectorTemplatesInternalServerError{}
}

/* ListSelectorTemplatesInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type ListSelectorTemplatesInternalServerError struct {
	Payload *models.RestError
}

func (o *ListSelectorTemplatesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] listSelectorTemplatesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListSelectorTemplatesInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListSelectorTemplatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
