// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// ListSelectorTemplatesReader is a Reader for the ListSelectorTemplates structure.
type ListSelectorTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSelectorTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSelectorTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListSelectorTemplatesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListSelectorTemplatesOK creates a ListSelectorTemplatesOK with default headers values
func NewListSelectorTemplatesOK() *ListSelectorTemplatesOK {
	return &ListSelectorTemplatesOK{}
}

/*
ListSelectorTemplatesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListSelectorTemplatesOK struct {
	Payload *models.EntListSelectorTemplatesResponse
}

// IsSuccess returns true when this list selector templates o k response has a 2xx status code
func (o *ListSelectorTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list selector templates o k response has a 3xx status code
func (o *ListSelectorTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list selector templates o k response has a 4xx status code
func (o *ListSelectorTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list selector templates o k response has a 5xx status code
func (o *ListSelectorTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list selector templates o k response a status code equal to that given
func (o *ListSelectorTemplatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list selector templates o k response
func (o *ListSelectorTemplatesOK) Code() int {
	return 200
}

func (o *ListSelectorTemplatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] listSelectorTemplatesOK %s", 200, payload)
}

func (o *ListSelectorTemplatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] listSelectorTemplatesOK %s", 200, payload)
}

func (o *ListSelectorTemplatesOK) GetPayload() *models.EntListSelectorTemplatesResponse {
	return o.Payload
}

func (o *ListSelectorTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntListSelectorTemplatesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSelectorTemplatesDefault creates a ListSelectorTemplatesDefault with default headers values
func NewListSelectorTemplatesDefault(code int) *ListSelectorTemplatesDefault {
	return &ListSelectorTemplatesDefault{
		_statusCode: code,
	}
}

/*
ListSelectorTemplatesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListSelectorTemplatesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this list selector templates default response has a 2xx status code
func (o *ListSelectorTemplatesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list selector templates default response has a 3xx status code
func (o *ListSelectorTemplatesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list selector templates default response has a 4xx status code
func (o *ListSelectorTemplatesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list selector templates default response has a 5xx status code
func (o *ListSelectorTemplatesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list selector templates default response a status code equal to that given
func (o *ListSelectorTemplatesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list selector templates default response
func (o *ListSelectorTemplatesDefault) Code() int {
	return o._statusCode
}

func (o *ListSelectorTemplatesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] ListSelectorTemplates default %s", o._statusCode, payload)
}

func (o *ListSelectorTemplatesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /scheduler/templates/selectors][%d] ListSelectorTemplates default %s", o._statusCode, payload)
}

func (o *ListSelectorTemplatesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ListSelectorTemplatesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
