// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// ListDocTemplatesReader is a Reader for the ListDocTemplates structure.
type ListDocTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDocTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDocTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListDocTemplatesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListDocTemplatesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListDocTemplatesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListDocTemplatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListDocTemplatesOK creates a ListDocTemplatesOK with default headers values
func NewListDocTemplatesOK() *ListDocTemplatesOK {
	return &ListDocTemplatesOK{}
}

/* ListDocTemplatesOK describes a response with status code 200, with default header values.

ListDocTemplatesOK list doc templates o k
*/
type ListDocTemplatesOK struct {
	Payload *models.EntDocTemplatesResponse
}

func (o *ListDocTemplatesOK) Error() string {
	return fmt.Sprintf("[GET /scheduler/templates/docs/{Type}][%d] listDocTemplatesOK  %+v", 200, o.Payload)
}
func (o *ListDocTemplatesOK) GetPayload() *models.EntDocTemplatesResponse {
	return o.Payload
}

func (o *ListDocTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntDocTemplatesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDocTemplatesUnauthorized creates a ListDocTemplatesUnauthorized with default headers values
func NewListDocTemplatesUnauthorized() *ListDocTemplatesUnauthorized {
	return &ListDocTemplatesUnauthorized{}
}

/* ListDocTemplatesUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type ListDocTemplatesUnauthorized struct {
}

func (o *ListDocTemplatesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /scheduler/templates/docs/{Type}][%d] listDocTemplatesUnauthorized ", 401)
}

func (o *ListDocTemplatesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListDocTemplatesForbidden creates a ListDocTemplatesForbidden with default headers values
func NewListDocTemplatesForbidden() *ListDocTemplatesForbidden {
	return &ListDocTemplatesForbidden{}
}

/* ListDocTemplatesForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type ListDocTemplatesForbidden struct {
	Payload *models.RestError
}

func (o *ListDocTemplatesForbidden) Error() string {
	return fmt.Sprintf("[GET /scheduler/templates/docs/{Type}][%d] listDocTemplatesForbidden  %+v", 403, o.Payload)
}
func (o *ListDocTemplatesForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListDocTemplatesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDocTemplatesNotFound creates a ListDocTemplatesNotFound with default headers values
func NewListDocTemplatesNotFound() *ListDocTemplatesNotFound {
	return &ListDocTemplatesNotFound{}
}

/* ListDocTemplatesNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type ListDocTemplatesNotFound struct {
	Payload *models.RestError
}

func (o *ListDocTemplatesNotFound) Error() string {
	return fmt.Sprintf("[GET /scheduler/templates/docs/{Type}][%d] listDocTemplatesNotFound  %+v", 404, o.Payload)
}
func (o *ListDocTemplatesNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListDocTemplatesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDocTemplatesInternalServerError creates a ListDocTemplatesInternalServerError with default headers values
func NewListDocTemplatesInternalServerError() *ListDocTemplatesInternalServerError {
	return &ListDocTemplatesInternalServerError{}
}

/* ListDocTemplatesInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type ListDocTemplatesInternalServerError struct {
	Payload *models.RestError
}

func (o *ListDocTemplatesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /scheduler/templates/docs/{Type}][%d] listDocTemplatesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListDocTemplatesInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListDocTemplatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
