// Code generated by go-swagger; DO NOT EDIT.

package scheduler_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// PutJobTemplateReader is a Reader for the PutJobTemplate structure.
type PutJobTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutJobTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutJobTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutJobTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutJobTemplateOK creates a PutJobTemplateOK with default headers values
func NewPutJobTemplateOK() *PutJobTemplateOK {
	return &PutJobTemplateOK{}
}

/*
PutJobTemplateOK describes a response with status code 200, with default header values.

A successful response.
*/
type PutJobTemplateOK struct {
	Payload *models.EntPutJobTemplateResponse
}

// IsSuccess returns true when this put job template o k response has a 2xx status code
func (o *PutJobTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put job template o k response has a 3xx status code
func (o *PutJobTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put job template o k response has a 4xx status code
func (o *PutJobTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put job template o k response has a 5xx status code
func (o *PutJobTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put job template o k response a status code equal to that given
func (o *PutJobTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put job template o k response
func (o *PutJobTemplateOK) Code() int {
	return 200
}

func (o *PutJobTemplateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /scheduler/templates/jobs/{Name}][%d] putJobTemplateOK %s", 200, payload)
}

func (o *PutJobTemplateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /scheduler/templates/jobs/{Name}][%d] putJobTemplateOK %s", 200, payload)
}

func (o *PutJobTemplateOK) GetPayload() *models.EntPutJobTemplateResponse {
	return o.Payload
}

func (o *PutJobTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntPutJobTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutJobTemplateDefault creates a PutJobTemplateDefault with default headers values
func NewPutJobTemplateDefault(code int) *PutJobTemplateDefault {
	return &PutJobTemplateDefault{
		_statusCode: code,
	}
}

/*
PutJobTemplateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PutJobTemplateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this put job template default response has a 2xx status code
func (o *PutJobTemplateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put job template default response has a 3xx status code
func (o *PutJobTemplateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put job template default response has a 4xx status code
func (o *PutJobTemplateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put job template default response has a 5xx status code
func (o *PutJobTemplateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put job template default response a status code equal to that given
func (o *PutJobTemplateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put job template default response
func (o *PutJobTemplateDefault) Code() int {
	return o._statusCode
}

func (o *PutJobTemplateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /scheduler/templates/jobs/{Name}][%d] PutJobTemplate default %s", o._statusCode, payload)
}

func (o *PutJobTemplateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /scheduler/templates/jobs/{Name}][%d] PutJobTemplate default %s", o._statusCode, payload)
}

func (o *PutJobTemplateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PutJobTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PutJobTemplateBody EntPutJobTemplateRequest
swagger:model PutJobTemplateBody
*/
type PutJobTemplateBody struct {

	// job
	Job *models.JobsJob `json:"Job,omitempty"`
}

// Validate validates this put job template body
func (o *PutJobTemplateBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateJob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutJobTemplateBody) validateJob(formats strfmt.Registry) error {
	if swag.IsZero(o.Job) { // not required
		return nil
	}

	if o.Job != nil {
		if err := o.Job.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "Job")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "Job")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this put job template body based on the context it is used
func (o *PutJobTemplateBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateJob(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutJobTemplateBody) contextValidateJob(ctx context.Context, formats strfmt.Registry) error {

	if o.Job != nil {

		if swag.IsZero(o.Job) { // not required
			return nil
		}

		if err := o.Job.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "Job")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "Job")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutJobTemplateBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutJobTemplateBody) UnmarshalBinary(b []byte) error {
	var res PutJobTemplateBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
