// Code generated by go-swagger; DO NOT EDIT.

package enterprise_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteOAuth2ClientReader is a Reader for the DeleteOAuth2Client structure.
type DeleteOAuth2ClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOAuth2ClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteOAuth2ClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteOAuth2ClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteOAuth2ClientOK creates a DeleteOAuth2ClientOK with default headers values
func NewDeleteOAuth2ClientOK() *DeleteOAuth2ClientOK {
	return &DeleteOAuth2ClientOK{}
}

/*
DeleteOAuth2ClientOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteOAuth2ClientOK struct {
	Payload *models.EntOAuth2ClientResponse
}

// IsSuccess returns true when this delete o auth2 client o k response has a 2xx status code
func (o *DeleteOAuth2ClientOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete o auth2 client o k response has a 3xx status code
func (o *DeleteOAuth2ClientOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete o auth2 client o k response has a 4xx status code
func (o *DeleteOAuth2ClientOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete o auth2 client o k response has a 5xx status code
func (o *DeleteOAuth2ClientOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete o auth2 client o k response a status code equal to that given
func (o *DeleteOAuth2ClientOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete o auth2 client o k response
func (o *DeleteOAuth2ClientOK) Code() int {
	return 200
}

func (o *DeleteOAuth2ClientOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2clients/{client_id}][%d] deleteOAuth2ClientOK %s", 200, payload)
}

func (o *DeleteOAuth2ClientOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2clients/{client_id}][%d] deleteOAuth2ClientOK %s", 200, payload)
}

func (o *DeleteOAuth2ClientOK) GetPayload() *models.EntOAuth2ClientResponse {
	return o.Payload
}

func (o *DeleteOAuth2ClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntOAuth2ClientResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOAuth2ClientDefault creates a DeleteOAuth2ClientDefault with default headers values
func NewDeleteOAuth2ClientDefault(code int) *DeleteOAuth2ClientDefault {
	return &DeleteOAuth2ClientDefault{
		_statusCode: code,
	}
}

/*
DeleteOAuth2ClientDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteOAuth2ClientDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this delete o auth2 client default response has a 2xx status code
func (o *DeleteOAuth2ClientDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete o auth2 client default response has a 3xx status code
func (o *DeleteOAuth2ClientDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete o auth2 client default response has a 4xx status code
func (o *DeleteOAuth2ClientDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete o auth2 client default response has a 5xx status code
func (o *DeleteOAuth2ClientDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete o auth2 client default response a status code equal to that given
func (o *DeleteOAuth2ClientDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete o auth2 client default response
func (o *DeleteOAuth2ClientDefault) Code() int {
	return o._statusCode
}

func (o *DeleteOAuth2ClientDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2clients/{client_id}][%d] DeleteOAuth2Client default %s", o._statusCode, payload)
}

func (o *DeleteOAuth2ClientDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2clients/{client_id}][%d] DeleteOAuth2Client default %s", o._statusCode, payload)
}

func (o *DeleteOAuth2ClientDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *DeleteOAuth2ClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
