// Code generated by go-swagger; DO NOT EDIT.

package enterprise_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteVirtualNodeParams creates a new DeleteVirtualNodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteVirtualNodeParams() *DeleteVirtualNodeParams {
	return &DeleteVirtualNodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVirtualNodeParamsWithTimeout creates a new DeleteVirtualNodeParams object
// with the ability to set a timeout on a request.
func NewDeleteVirtualNodeParamsWithTimeout(timeout time.Duration) *DeleteVirtualNodeParams {
	return &DeleteVirtualNodeParams{
		timeout: timeout,
	}
}

// NewDeleteVirtualNodeParamsWithContext creates a new DeleteVirtualNodeParams object
// with the ability to set a context for a request.
func NewDeleteVirtualNodeParamsWithContext(ctx context.Context) *DeleteVirtualNodeParams {
	return &DeleteVirtualNodeParams{
		Context: ctx,
	}
}

// NewDeleteVirtualNodeParamsWithHTTPClient creates a new DeleteVirtualNodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteVirtualNodeParamsWithHTTPClient(client *http.Client) *DeleteVirtualNodeParams {
	return &DeleteVirtualNodeParams{
		HTTPClient: client,
	}
}

/* DeleteVirtualNodeParams contains all the parameters to send to the API endpoint
   for the delete virtual node operation.

   Typically these are written to a http.Request.
*/
type DeleteVirtualNodeParams struct {

	// UUID.
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete virtual node params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVirtualNodeParams) WithDefaults() *DeleteVirtualNodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete virtual node params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVirtualNodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete virtual node params
func (o *DeleteVirtualNodeParams) WithTimeout(timeout time.Duration) *DeleteVirtualNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete virtual node params
func (o *DeleteVirtualNodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete virtual node params
func (o *DeleteVirtualNodeParams) WithContext(ctx context.Context) *DeleteVirtualNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete virtual node params
func (o *DeleteVirtualNodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete virtual node params
func (o *DeleteVirtualNodeParams) WithHTTPClient(client *http.Client) *DeleteVirtualNodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete virtual node params
func (o *DeleteVirtualNodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the delete virtual node params
func (o *DeleteVirtualNodeParams) WithUUID(uuid string) *DeleteVirtualNodeParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete virtual node params
func (o *DeleteVirtualNodeParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVirtualNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Uuid
	if err := r.SetPathParam("Uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
