// Code generated by go-swagger; DO NOT EDIT.

package enterprise_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteOAuth2ClientReader is a Reader for the DeleteOAuth2Client structure.
type DeleteOAuth2ClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOAuth2ClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteOAuth2ClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteOAuth2ClientUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteOAuth2ClientForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteOAuth2ClientNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteOAuth2ClientInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteOAuth2ClientOK creates a DeleteOAuth2ClientOK with default headers values
func NewDeleteOAuth2ClientOK() *DeleteOAuth2ClientOK {
	return &DeleteOAuth2ClientOK{}
}

/* DeleteOAuth2ClientOK describes a response with status code 200, with default header values.

DeleteOAuth2ClientOK delete o auth2 client o k
*/
type DeleteOAuth2ClientOK struct {
	Payload *models.EntOAuth2ClientResponse
}

func (o *DeleteOAuth2ClientOK) Error() string {
	return fmt.Sprintf("[DELETE /config/oauth2clients/{ClientID}][%d] deleteOAuth2ClientOK  %+v", 200, o.Payload)
}
func (o *DeleteOAuth2ClientOK) GetPayload() *models.EntOAuth2ClientResponse {
	return o.Payload
}

func (o *DeleteOAuth2ClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntOAuth2ClientResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOAuth2ClientUnauthorized creates a DeleteOAuth2ClientUnauthorized with default headers values
func NewDeleteOAuth2ClientUnauthorized() *DeleteOAuth2ClientUnauthorized {
	return &DeleteOAuth2ClientUnauthorized{}
}

/* DeleteOAuth2ClientUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type DeleteOAuth2ClientUnauthorized struct {
}

func (o *DeleteOAuth2ClientUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /config/oauth2clients/{ClientID}][%d] deleteOAuth2ClientUnauthorized ", 401)
}

func (o *DeleteOAuth2ClientUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOAuth2ClientForbidden creates a DeleteOAuth2ClientForbidden with default headers values
func NewDeleteOAuth2ClientForbidden() *DeleteOAuth2ClientForbidden {
	return &DeleteOAuth2ClientForbidden{}
}

/* DeleteOAuth2ClientForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type DeleteOAuth2ClientForbidden struct {
	Payload *models.RestError
}

func (o *DeleteOAuth2ClientForbidden) Error() string {
	return fmt.Sprintf("[DELETE /config/oauth2clients/{ClientID}][%d] deleteOAuth2ClientForbidden  %+v", 403, o.Payload)
}
func (o *DeleteOAuth2ClientForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteOAuth2ClientForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOAuth2ClientNotFound creates a DeleteOAuth2ClientNotFound with default headers values
func NewDeleteOAuth2ClientNotFound() *DeleteOAuth2ClientNotFound {
	return &DeleteOAuth2ClientNotFound{}
}

/* DeleteOAuth2ClientNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type DeleteOAuth2ClientNotFound struct {
	Payload *models.RestError
}

func (o *DeleteOAuth2ClientNotFound) Error() string {
	return fmt.Sprintf("[DELETE /config/oauth2clients/{ClientID}][%d] deleteOAuth2ClientNotFound  %+v", 404, o.Payload)
}
func (o *DeleteOAuth2ClientNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteOAuth2ClientNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOAuth2ClientInternalServerError creates a DeleteOAuth2ClientInternalServerError with default headers values
func NewDeleteOAuth2ClientInternalServerError() *DeleteOAuth2ClientInternalServerError {
	return &DeleteOAuth2ClientInternalServerError{}
}

/* DeleteOAuth2ClientInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type DeleteOAuth2ClientInternalServerError struct {
	Payload *models.RestError
}

func (o *DeleteOAuth2ClientInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /config/oauth2clients/{ClientID}][%d] deleteOAuth2ClientInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteOAuth2ClientInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *DeleteOAuth2ClientInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
