// Code generated by go-swagger; DO NOT EDIT.

package enterprise_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// DeleteOAuth2ConnectorReader is a Reader for the DeleteOAuth2Connector structure.
type DeleteOAuth2ConnectorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOAuth2ConnectorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteOAuth2ConnectorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteOAuth2ConnectorDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteOAuth2ConnectorOK creates a DeleteOAuth2ConnectorOK with default headers values
func NewDeleteOAuth2ConnectorOK() *DeleteOAuth2ConnectorOK {
	return &DeleteOAuth2ConnectorOK{}
}

/*
DeleteOAuth2ConnectorOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteOAuth2ConnectorOK struct {
	Payload *models.EntOAuth2ConnectorResponse
}

// IsSuccess returns true when this delete o auth2 connector o k response has a 2xx status code
func (o *DeleteOAuth2ConnectorOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete o auth2 connector o k response has a 3xx status code
func (o *DeleteOAuth2ConnectorOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete o auth2 connector o k response has a 4xx status code
func (o *DeleteOAuth2ConnectorOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete o auth2 connector o k response has a 5xx status code
func (o *DeleteOAuth2ConnectorOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete o auth2 connector o k response a status code equal to that given
func (o *DeleteOAuth2ConnectorOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete o auth2 connector o k response
func (o *DeleteOAuth2ConnectorOK) Code() int {
	return 200
}

func (o *DeleteOAuth2ConnectorOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2connectors/{id}][%d] deleteOAuth2ConnectorOK %s", 200, payload)
}

func (o *DeleteOAuth2ConnectorOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2connectors/{id}][%d] deleteOAuth2ConnectorOK %s", 200, payload)
}

func (o *DeleteOAuth2ConnectorOK) GetPayload() *models.EntOAuth2ConnectorResponse {
	return o.Payload
}

func (o *DeleteOAuth2ConnectorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntOAuth2ConnectorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOAuth2ConnectorDefault creates a DeleteOAuth2ConnectorDefault with default headers values
func NewDeleteOAuth2ConnectorDefault(code int) *DeleteOAuth2ConnectorDefault {
	return &DeleteOAuth2ConnectorDefault{
		_statusCode: code,
	}
}

/*
DeleteOAuth2ConnectorDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeleteOAuth2ConnectorDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this delete o auth2 connector default response has a 2xx status code
func (o *DeleteOAuth2ConnectorDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete o auth2 connector default response has a 3xx status code
func (o *DeleteOAuth2ConnectorDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete o auth2 connector default response has a 4xx status code
func (o *DeleteOAuth2ConnectorDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete o auth2 connector default response has a 5xx status code
func (o *DeleteOAuth2ConnectorDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete o auth2 connector default response a status code equal to that given
func (o *DeleteOAuth2ConnectorDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete o auth2 connector default response
func (o *DeleteOAuth2ConnectorDefault) Code() int {
	return o._statusCode
}

func (o *DeleteOAuth2ConnectorDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2connectors/{id}][%d] DeleteOAuth2Connector default %s", o._statusCode, payload)
}

func (o *DeleteOAuth2ConnectorDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /config/oauth2connectors/{id}][%d] DeleteOAuth2Connector default %s", o._statusCode, payload)
}

func (o *DeleteOAuth2ConnectorDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *DeleteOAuth2ConnectorDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
