// Code generated by go-swagger; DO NOT EDIT.

package enterprise_config_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// ListOAuth2ConnectorsReader is a Reader for the ListOAuth2Connectors structure.
type ListOAuth2ConnectorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOAuth2ConnectorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOAuth2ConnectorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListOAuth2ConnectorsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOAuth2ConnectorsOK creates a ListOAuth2ConnectorsOK with default headers values
func NewListOAuth2ConnectorsOK() *ListOAuth2ConnectorsOK {
	return &ListOAuth2ConnectorsOK{}
}

/*
ListOAuth2ConnectorsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListOAuth2ConnectorsOK struct {
	Payload *models.EntOAuth2ConnectorCollection
}

// IsSuccess returns true when this list o auth2 connectors o k response has a 2xx status code
func (o *ListOAuth2ConnectorsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list o auth2 connectors o k response has a 3xx status code
func (o *ListOAuth2ConnectorsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list o auth2 connectors o k response has a 4xx status code
func (o *ListOAuth2ConnectorsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list o auth2 connectors o k response has a 5xx status code
func (o *ListOAuth2ConnectorsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list o auth2 connectors o k response a status code equal to that given
func (o *ListOAuth2ConnectorsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list o auth2 connectors o k response
func (o *ListOAuth2ConnectorsOK) Code() int {
	return 200
}

func (o *ListOAuth2ConnectorsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config/oauth2connectors][%d] listOAuth2ConnectorsOK %s", 200, payload)
}

func (o *ListOAuth2ConnectorsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config/oauth2connectors][%d] listOAuth2ConnectorsOK %s", 200, payload)
}

func (o *ListOAuth2ConnectorsOK) GetPayload() *models.EntOAuth2ConnectorCollection {
	return o.Payload
}

func (o *ListOAuth2ConnectorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntOAuth2ConnectorCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOAuth2ConnectorsDefault creates a ListOAuth2ConnectorsDefault with default headers values
func NewListOAuth2ConnectorsDefault(code int) *ListOAuth2ConnectorsDefault {
	return &ListOAuth2ConnectorsDefault{
		_statusCode: code,
	}
}

/*
ListOAuth2ConnectorsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListOAuth2ConnectorsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this list o auth2 connectors default response has a 2xx status code
func (o *ListOAuth2ConnectorsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list o auth2 connectors default response has a 3xx status code
func (o *ListOAuth2ConnectorsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list o auth2 connectors default response has a 4xx status code
func (o *ListOAuth2ConnectorsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list o auth2 connectors default response has a 5xx status code
func (o *ListOAuth2ConnectorsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list o auth2 connectors default response a status code equal to that given
func (o *ListOAuth2ConnectorsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list o auth2 connectors default response
func (o *ListOAuth2ConnectorsDefault) Code() int {
	return o._statusCode
}

func (o *ListOAuth2ConnectorsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config/oauth2connectors][%d] ListOAuth2Connectors default %s", o._statusCode, payload)
}

func (o *ListOAuth2ConnectorsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config/oauth2connectors][%d] ListOAuth2Connectors default %s", o._statusCode, payload)
}

func (o *ListOAuth2ConnectorsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ListOAuth2ConnectorsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
