// Code generated by go-swagger; DO NOT EDIT.

package enterprise_policy_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListBansParams creates a new ListBansParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListBansParams() *ListBansParams {
	return &ListBansParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListBansParamsWithTimeout creates a new ListBansParams object
// with the ability to set a timeout on a request.
func NewListBansParamsWithTimeout(timeout time.Duration) *ListBansParams {
	return &ListBansParams{
		timeout: timeout,
	}
}

// NewListBansParamsWithContext creates a new ListBansParams object
// with the ability to set a context for a request.
func NewListBansParamsWithContext(ctx context.Context) *ListBansParams {
	return &ListBansParams{
		Context: ctx,
	}
}

// NewListBansParamsWithHTTPClient creates a new ListBansParams object
// with the ability to set a custom HTTPClient for a request.
func NewListBansParamsWithHTTPClient(client *http.Client) *ListBansParams {
	return &ListBansParams{
		HTTPClient: client,
	}
}

/* ListBansParams contains all the parameters to send to the API endpoint
   for the list bans operation.

   Typically these are written to a http.Request.
*/
type ListBansParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list bans params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListBansParams) WithDefaults() *ListBansParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list bans params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListBansParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list bans params
func (o *ListBansParams) WithTimeout(timeout time.Duration) *ListBansParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list bans params
func (o *ListBansParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list bans params
func (o *ListBansParams) WithContext(ctx context.Context) *ListBansParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list bans params
func (o *ListBansParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list bans params
func (o *ListBansParams) WithHTTPClient(client *http.Client) *ListBansParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list bans params
func (o *ListBansParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListBansParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
