// Code generated by go-swagger; DO NOT EDIT.

package enterprise_policy_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// PutPolicyReader is a Reader for the PutPolicy structure.
type PutPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPutPolicyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutPolicyForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutPolicyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutPolicyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutPolicyOK creates a PutPolicyOK with default headers values
func NewPutPolicyOK() *PutPolicyOK {
	return &PutPolicyOK{}
}

/* PutPolicyOK describes a response with status code 200, with default header values.

PutPolicyOK put policy o k
*/
type PutPolicyOK struct {
	Payload *models.IdmPolicyGroup
}

func (o *PutPolicyOK) Error() string {
	return fmt.Sprintf("[PUT /policy][%d] putPolicyOK  %+v", 200, o.Payload)
}
func (o *PutPolicyOK) GetPayload() *models.IdmPolicyGroup {
	return o.Payload
}

func (o *PutPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IdmPolicyGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutPolicyUnauthorized creates a PutPolicyUnauthorized with default headers values
func NewPutPolicyUnauthorized() *PutPolicyUnauthorized {
	return &PutPolicyUnauthorized{}
}

/* PutPolicyUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type PutPolicyUnauthorized struct {
}

func (o *PutPolicyUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /policy][%d] putPolicyUnauthorized ", 401)
}

func (o *PutPolicyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutPolicyForbidden creates a PutPolicyForbidden with default headers values
func NewPutPolicyForbidden() *PutPolicyForbidden {
	return &PutPolicyForbidden{}
}

/* PutPolicyForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type PutPolicyForbidden struct {
	Payload *models.RestError
}

func (o *PutPolicyForbidden) Error() string {
	return fmt.Sprintf("[PUT /policy][%d] putPolicyForbidden  %+v", 403, o.Payload)
}
func (o *PutPolicyForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *PutPolicyForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutPolicyNotFound creates a PutPolicyNotFound with default headers values
func NewPutPolicyNotFound() *PutPolicyNotFound {
	return &PutPolicyNotFound{}
}

/* PutPolicyNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type PutPolicyNotFound struct {
	Payload *models.RestError
}

func (o *PutPolicyNotFound) Error() string {
	return fmt.Sprintf("[PUT /policy][%d] putPolicyNotFound  %+v", 404, o.Payload)
}
func (o *PutPolicyNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *PutPolicyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutPolicyInternalServerError creates a PutPolicyInternalServerError with default headers values
func NewPutPolicyInternalServerError() *PutPolicyInternalServerError {
	return &PutPolicyInternalServerError{}
}

/* PutPolicyInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type PutPolicyInternalServerError struct {
	Payload *models.RestError
}

func (o *PutPolicyInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /policy][%d] putPolicyInternalServerError  %+v", 500, o.Payload)
}
func (o *PutPolicyInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *PutPolicyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
