// Code generated by go-swagger; DO NOT EDIT.

package enterprise_policy_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// UpdateIPsReader is a Reader for the UpdateIPs structure.
type UpdateIPsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateIPsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateIPsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateIPsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateIPsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateIPsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateIPsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateIPsOK creates a UpdateIPsOK with default headers values
func NewUpdateIPsOK() *UpdateIPsOK {
	return &UpdateIPsOK{}
}

/* UpdateIPsOK describes a response with status code 200, with default header values.

UpdateIPsOK update i ps o k
*/
type UpdateIPsOK struct {
	Payload *models.IpbanIPsCollection
}

func (o *UpdateIPsOK) Error() string {
	return fmt.Sprintf("[POST /policy/iplists][%d] updateIPsOK  %+v", 200, o.Payload)
}
func (o *UpdateIPsOK) GetPayload() *models.IpbanIPsCollection {
	return o.Payload
}

func (o *UpdateIPsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpbanIPsCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIPsUnauthorized creates a UpdateIPsUnauthorized with default headers values
func NewUpdateIPsUnauthorized() *UpdateIPsUnauthorized {
	return &UpdateIPsUnauthorized{}
}

/* UpdateIPsUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type UpdateIPsUnauthorized struct {
}

func (o *UpdateIPsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /policy/iplists][%d] updateIPsUnauthorized ", 401)
}

func (o *UpdateIPsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateIPsForbidden creates a UpdateIPsForbidden with default headers values
func NewUpdateIPsForbidden() *UpdateIPsForbidden {
	return &UpdateIPsForbidden{}
}

/* UpdateIPsForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type UpdateIPsForbidden struct {
	Payload *models.RestError
}

func (o *UpdateIPsForbidden) Error() string {
	return fmt.Sprintf("[POST /policy/iplists][%d] updateIPsForbidden  %+v", 403, o.Payload)
}
func (o *UpdateIPsForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *UpdateIPsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIPsNotFound creates a UpdateIPsNotFound with default headers values
func NewUpdateIPsNotFound() *UpdateIPsNotFound {
	return &UpdateIPsNotFound{}
}

/* UpdateIPsNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type UpdateIPsNotFound struct {
	Payload *models.RestError
}

func (o *UpdateIPsNotFound) Error() string {
	return fmt.Sprintf("[POST /policy/iplists][%d] updateIPsNotFound  %+v", 404, o.Payload)
}
func (o *UpdateIPsNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *UpdateIPsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIPsInternalServerError creates a UpdateIPsInternalServerError with default headers values
func NewUpdateIPsInternalServerError() *UpdateIPsInternalServerError {
	return &UpdateIPsInternalServerError{}
}

/* UpdateIPsInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type UpdateIPsInternalServerError struct {
	Payload *models.RestError
}

func (o *UpdateIPsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /policy/iplists][%d] updateIPsInternalServerError  %+v", 500, o.Payload)
}
func (o *UpdateIPsInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *UpdateIPsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
