// Code generated by go-swagger; DO NOT EDIT.

package enterprise_policy_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// UpdateIPsReader is a Reader for the UpdateIPs structure.
type UpdateIPsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateIPsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateIPsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateIPsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateIPsOK creates a UpdateIPsOK with default headers values
func NewUpdateIPsOK() *UpdateIPsOK {
	return &UpdateIPsOK{}
}

/*
UpdateIPsOK describes a response with status code 200, with default header values.

A successful response.
*/
type UpdateIPsOK struct {
	Payload *models.IpbanIPsCollection
}

// IsSuccess returns true when this update i ps o k response has a 2xx status code
func (o *UpdateIPsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update i ps o k response has a 3xx status code
func (o *UpdateIPsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update i ps o k response has a 4xx status code
func (o *UpdateIPsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update i ps o k response has a 5xx status code
func (o *UpdateIPsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update i ps o k response a status code equal to that given
func (o *UpdateIPsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update i ps o k response
func (o *UpdateIPsOK) Code() int {
	return 200
}

func (o *UpdateIPsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /policy/iplists][%d] updateIPsOK %s", 200, payload)
}

func (o *UpdateIPsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /policy/iplists][%d] updateIPsOK %s", 200, payload)
}

func (o *UpdateIPsOK) GetPayload() *models.IpbanIPsCollection {
	return o.Payload
}

func (o *UpdateIPsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpbanIPsCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIPsDefault creates a UpdateIPsDefault with default headers values
func NewUpdateIPsDefault(code int) *UpdateIPsDefault {
	return &UpdateIPsDefault{
		_statusCode: code,
	}
}

/*
UpdateIPsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type UpdateIPsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this update i ps default response has a 2xx status code
func (o *UpdateIPsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update i ps default response has a 3xx status code
func (o *UpdateIPsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update i ps default response has a 4xx status code
func (o *UpdateIPsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update i ps default response has a 5xx status code
func (o *UpdateIPsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update i ps default response a status code equal to that given
func (o *UpdateIPsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update i ps default response
func (o *UpdateIPsDefault) Code() int {
	return o._statusCode
}

func (o *UpdateIPsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /policy/iplists][%d] UpdateIPs default %s", o._statusCode, payload)
}

func (o *UpdateIPsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /policy/iplists][%d] UpdateIPs default %s", o._statusCode, payload)
}

func (o *UpdateIPsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *UpdateIPsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
