// Code generated by go-swagger; DO NOT EDIT.

package enterprise_templates_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// CreateNodeTemplateReader is a Reader for the CreateNodeTemplate structure.
type CreateNodeTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNodeTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateNodeTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateNodeTemplateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateNodeTemplateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateNodeTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateNodeTemplateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateNodeTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateNodeTemplateOK creates a CreateNodeTemplateOK with default headers values
func NewCreateNodeTemplateOK() *CreateNodeTemplateOK {
	return &CreateNodeTemplateOK{}
}

/*
CreateNodeTemplateOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateNodeTemplateOK struct {
	Payload *models.EntCreateNodeTemplateResponse
}

// IsSuccess returns true when this create node template o k response has a 2xx status code
func (o *CreateNodeTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create node template o k response has a 3xx status code
func (o *CreateNodeTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create node template o k response has a 4xx status code
func (o *CreateNodeTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create node template o k response has a 5xx status code
func (o *CreateNodeTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create node template o k response a status code equal to that given
func (o *CreateNodeTemplateOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateNodeTemplateOK) Error() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateOK  %+v", 200, o.Payload)
}

func (o *CreateNodeTemplateOK) String() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateOK  %+v", 200, o.Payload)
}

func (o *CreateNodeTemplateOK) GetPayload() *models.EntCreateNodeTemplateResponse {
	return o.Payload
}

func (o *CreateNodeTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntCreateNodeTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNodeTemplateUnauthorized creates a CreateNodeTemplateUnauthorized with default headers values
func NewCreateNodeTemplateUnauthorized() *CreateNodeTemplateUnauthorized {
	return &CreateNodeTemplateUnauthorized{}
}

/*
CreateNodeTemplateUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type CreateNodeTemplateUnauthorized struct {
}

// IsSuccess returns true when this create node template unauthorized response has a 2xx status code
func (o *CreateNodeTemplateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create node template unauthorized response has a 3xx status code
func (o *CreateNodeTemplateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create node template unauthorized response has a 4xx status code
func (o *CreateNodeTemplateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create node template unauthorized response has a 5xx status code
func (o *CreateNodeTemplateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create node template unauthorized response a status code equal to that given
func (o *CreateNodeTemplateUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateNodeTemplateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateUnauthorized ", 401)
}

func (o *CreateNodeTemplateUnauthorized) String() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateUnauthorized ", 401)
}

func (o *CreateNodeTemplateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNodeTemplateForbidden creates a CreateNodeTemplateForbidden with default headers values
func NewCreateNodeTemplateForbidden() *CreateNodeTemplateForbidden {
	return &CreateNodeTemplateForbidden{}
}

/*
CreateNodeTemplateForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type CreateNodeTemplateForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this create node template forbidden response has a 2xx status code
func (o *CreateNodeTemplateForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create node template forbidden response has a 3xx status code
func (o *CreateNodeTemplateForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create node template forbidden response has a 4xx status code
func (o *CreateNodeTemplateForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create node template forbidden response has a 5xx status code
func (o *CreateNodeTemplateForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create node template forbidden response a status code equal to that given
func (o *CreateNodeTemplateForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateNodeTemplateForbidden) Error() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateForbidden  %+v", 403, o.Payload)
}

func (o *CreateNodeTemplateForbidden) String() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateForbidden  %+v", 403, o.Payload)
}

func (o *CreateNodeTemplateForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *CreateNodeTemplateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNodeTemplateNotFound creates a CreateNodeTemplateNotFound with default headers values
func NewCreateNodeTemplateNotFound() *CreateNodeTemplateNotFound {
	return &CreateNodeTemplateNotFound{}
}

/*
CreateNodeTemplateNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type CreateNodeTemplateNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this create node template not found response has a 2xx status code
func (o *CreateNodeTemplateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create node template not found response has a 3xx status code
func (o *CreateNodeTemplateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create node template not found response has a 4xx status code
func (o *CreateNodeTemplateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create node template not found response has a 5xx status code
func (o *CreateNodeTemplateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create node template not found response a status code equal to that given
func (o *CreateNodeTemplateNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateNodeTemplateNotFound) Error() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateNotFound  %+v", 404, o.Payload)
}

func (o *CreateNodeTemplateNotFound) String() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateNotFound  %+v", 404, o.Payload)
}

func (o *CreateNodeTemplateNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *CreateNodeTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNodeTemplateInternalServerError creates a CreateNodeTemplateInternalServerError with default headers values
func NewCreateNodeTemplateInternalServerError() *CreateNodeTemplateInternalServerError {
	return &CreateNodeTemplateInternalServerError{}
}

/*
CreateNodeTemplateInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type CreateNodeTemplateInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this create node template internal server error response has a 2xx status code
func (o *CreateNodeTemplateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create node template internal server error response has a 3xx status code
func (o *CreateNodeTemplateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create node template internal server error response has a 4xx status code
func (o *CreateNodeTemplateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create node template internal server error response has a 5xx status code
func (o *CreateNodeTemplateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create node template internal server error response a status code equal to that given
func (o *CreateNodeTemplateInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateNodeTemplateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateNodeTemplateInternalServerError) String() string {
	return fmt.Sprintf("[POST /templates/node][%d] createNodeTemplateInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateNodeTemplateInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *CreateNodeTemplateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNodeTemplateDefault creates a CreateNodeTemplateDefault with default headers values
func NewCreateNodeTemplateDefault(code int) *CreateNodeTemplateDefault {
	return &CreateNodeTemplateDefault{
		_statusCode: code,
	}
}

/*
CreateNodeTemplateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CreateNodeTemplateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the create node template default response
func (o *CreateNodeTemplateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this create node template default response has a 2xx status code
func (o *CreateNodeTemplateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create node template default response has a 3xx status code
func (o *CreateNodeTemplateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create node template default response has a 4xx status code
func (o *CreateNodeTemplateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create node template default response has a 5xx status code
func (o *CreateNodeTemplateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create node template default response a status code equal to that given
func (o *CreateNodeTemplateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *CreateNodeTemplateDefault) Error() string {
	return fmt.Sprintf("[POST /templates/node][%d] CreateNodeTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *CreateNodeTemplateDefault) String() string {
	return fmt.Sprintf("[POST /templates/node][%d] CreateNodeTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *CreateNodeTemplateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *CreateNodeTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
