// Code generated by go-swagger; DO NOT EDIT.

package enterprise_token_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// GeneratePersonalAccessTokenReader is a Reader for the GeneratePersonalAccessToken structure.
type GeneratePersonalAccessTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GeneratePersonalAccessTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGeneratePersonalAccessTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGeneratePersonalAccessTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGeneratePersonalAccessTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGeneratePersonalAccessTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGeneratePersonalAccessTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGeneratePersonalAccessTokenOK creates a GeneratePersonalAccessTokenOK with default headers values
func NewGeneratePersonalAccessTokenOK() *GeneratePersonalAccessTokenOK {
	return &GeneratePersonalAccessTokenOK{}
}

/* GeneratePersonalAccessTokenOK describes a response with status code 200, with default header values.

GeneratePersonalAccessTokenOK generate personal access token o k
*/
type GeneratePersonalAccessTokenOK struct {
	Payload *models.EntPersonalAccessTokenResponse
}

func (o *GeneratePersonalAccessTokenOK) Error() string {
	return fmt.Sprintf("[POST /auth/token/personal][%d] generatePersonalAccessTokenOK  %+v", 200, o.Payload)
}
func (o *GeneratePersonalAccessTokenOK) GetPayload() *models.EntPersonalAccessTokenResponse {
	return o.Payload
}

func (o *GeneratePersonalAccessTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntPersonalAccessTokenResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGeneratePersonalAccessTokenUnauthorized creates a GeneratePersonalAccessTokenUnauthorized with default headers values
func NewGeneratePersonalAccessTokenUnauthorized() *GeneratePersonalAccessTokenUnauthorized {
	return &GeneratePersonalAccessTokenUnauthorized{}
}

/* GeneratePersonalAccessTokenUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type GeneratePersonalAccessTokenUnauthorized struct {
}

func (o *GeneratePersonalAccessTokenUnauthorized) Error() string {
	return fmt.Sprintf("[POST /auth/token/personal][%d] generatePersonalAccessTokenUnauthorized ", 401)
}

func (o *GeneratePersonalAccessTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGeneratePersonalAccessTokenForbidden creates a GeneratePersonalAccessTokenForbidden with default headers values
func NewGeneratePersonalAccessTokenForbidden() *GeneratePersonalAccessTokenForbidden {
	return &GeneratePersonalAccessTokenForbidden{}
}

/* GeneratePersonalAccessTokenForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type GeneratePersonalAccessTokenForbidden struct {
	Payload *models.RestError
}

func (o *GeneratePersonalAccessTokenForbidden) Error() string {
	return fmt.Sprintf("[POST /auth/token/personal][%d] generatePersonalAccessTokenForbidden  %+v", 403, o.Payload)
}
func (o *GeneratePersonalAccessTokenForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *GeneratePersonalAccessTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGeneratePersonalAccessTokenNotFound creates a GeneratePersonalAccessTokenNotFound with default headers values
func NewGeneratePersonalAccessTokenNotFound() *GeneratePersonalAccessTokenNotFound {
	return &GeneratePersonalAccessTokenNotFound{}
}

/* GeneratePersonalAccessTokenNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type GeneratePersonalAccessTokenNotFound struct {
	Payload *models.RestError
}

func (o *GeneratePersonalAccessTokenNotFound) Error() string {
	return fmt.Sprintf("[POST /auth/token/personal][%d] generatePersonalAccessTokenNotFound  %+v", 404, o.Payload)
}
func (o *GeneratePersonalAccessTokenNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *GeneratePersonalAccessTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGeneratePersonalAccessTokenInternalServerError creates a GeneratePersonalAccessTokenInternalServerError with default headers values
func NewGeneratePersonalAccessTokenInternalServerError() *GeneratePersonalAccessTokenInternalServerError {
	return &GeneratePersonalAccessTokenInternalServerError{}
}

/* GeneratePersonalAccessTokenInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type GeneratePersonalAccessTokenInternalServerError struct {
	Payload *models.RestError
}

func (o *GeneratePersonalAccessTokenInternalServerError) Error() string {
	return fmt.Sprintf("[POST /auth/token/personal][%d] generatePersonalAccessTokenInternalServerError  %+v", 500, o.Payload)
}
func (o *GeneratePersonalAccessTokenInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *GeneratePersonalAccessTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
