// Code generated by go-swagger; DO NOT EDIT.

package enterprise_token_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// NewImpersonatePersonalAccessTokenParams creates a new ImpersonatePersonalAccessTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImpersonatePersonalAccessTokenParams() *ImpersonatePersonalAccessTokenParams {
	return &ImpersonatePersonalAccessTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImpersonatePersonalAccessTokenParamsWithTimeout creates a new ImpersonatePersonalAccessTokenParams object
// with the ability to set a timeout on a request.
func NewImpersonatePersonalAccessTokenParamsWithTimeout(timeout time.Duration) *ImpersonatePersonalAccessTokenParams {
	return &ImpersonatePersonalAccessTokenParams{
		timeout: timeout,
	}
}

// NewImpersonatePersonalAccessTokenParamsWithContext creates a new ImpersonatePersonalAccessTokenParams object
// with the ability to set a context for a request.
func NewImpersonatePersonalAccessTokenParamsWithContext(ctx context.Context) *ImpersonatePersonalAccessTokenParams {
	return &ImpersonatePersonalAccessTokenParams{
		Context: ctx,
	}
}

// NewImpersonatePersonalAccessTokenParamsWithHTTPClient creates a new ImpersonatePersonalAccessTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewImpersonatePersonalAccessTokenParamsWithHTTPClient(client *http.Client) *ImpersonatePersonalAccessTokenParams {
	return &ImpersonatePersonalAccessTokenParams{
		HTTPClient: client,
	}
}

/*
ImpersonatePersonalAccessTokenParams contains all the parameters to send to the API endpoint

	for the impersonate personal access token operation.

	Typically these are written to a http.Request.
*/
type ImpersonatePersonalAccessTokenParams struct {

	// Body.
	Body *models.EntPersonalAccessTokenRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the impersonate personal access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImpersonatePersonalAccessTokenParams) WithDefaults() *ImpersonatePersonalAccessTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the impersonate personal access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImpersonatePersonalAccessTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) WithTimeout(timeout time.Duration) *ImpersonatePersonalAccessTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) WithContext(ctx context.Context) *ImpersonatePersonalAccessTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) WithHTTPClient(client *http.Client) *ImpersonatePersonalAccessTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) WithBody(body *models.EntPersonalAccessTokenRequest) *ImpersonatePersonalAccessTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the impersonate personal access token params
func (o *ImpersonatePersonalAccessTokenParams) SetBody(body *models.EntPersonalAccessTokenRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ImpersonatePersonalAccessTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
