// Code generated by go-swagger; DO NOT EDIT.

package enterprise_token_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// ListPersonalAccessTokensReader is a Reader for the ListPersonalAccessTokens structure.
type ListPersonalAccessTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPersonalAccessTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPersonalAccessTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListPersonalAccessTokensUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListPersonalAccessTokensForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListPersonalAccessTokensNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListPersonalAccessTokensInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListPersonalAccessTokensDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListPersonalAccessTokensOK creates a ListPersonalAccessTokensOK with default headers values
func NewListPersonalAccessTokensOK() *ListPersonalAccessTokensOK {
	return &ListPersonalAccessTokensOK{}
}

/*
ListPersonalAccessTokensOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListPersonalAccessTokensOK struct {
	Payload *models.AuthPatListResponse
}

// IsSuccess returns true when this list personal access tokens o k response has a 2xx status code
func (o *ListPersonalAccessTokensOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list personal access tokens o k response has a 3xx status code
func (o *ListPersonalAccessTokensOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list personal access tokens o k response has a 4xx status code
func (o *ListPersonalAccessTokensOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list personal access tokens o k response has a 5xx status code
func (o *ListPersonalAccessTokensOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list personal access tokens o k response a status code equal to that given
func (o *ListPersonalAccessTokensOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListPersonalAccessTokensOK) Error() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensOK  %+v", 200, o.Payload)
}

func (o *ListPersonalAccessTokensOK) String() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensOK  %+v", 200, o.Payload)
}

func (o *ListPersonalAccessTokensOK) GetPayload() *models.AuthPatListResponse {
	return o.Payload
}

func (o *ListPersonalAccessTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthPatListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPersonalAccessTokensUnauthorized creates a ListPersonalAccessTokensUnauthorized with default headers values
func NewListPersonalAccessTokensUnauthorized() *ListPersonalAccessTokensUnauthorized {
	return &ListPersonalAccessTokensUnauthorized{}
}

/*
ListPersonalAccessTokensUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type ListPersonalAccessTokensUnauthorized struct {
}

// IsSuccess returns true when this list personal access tokens unauthorized response has a 2xx status code
func (o *ListPersonalAccessTokensUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list personal access tokens unauthorized response has a 3xx status code
func (o *ListPersonalAccessTokensUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list personal access tokens unauthorized response has a 4xx status code
func (o *ListPersonalAccessTokensUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list personal access tokens unauthorized response has a 5xx status code
func (o *ListPersonalAccessTokensUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list personal access tokens unauthorized response a status code equal to that given
func (o *ListPersonalAccessTokensUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *ListPersonalAccessTokensUnauthorized) Error() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensUnauthorized ", 401)
}

func (o *ListPersonalAccessTokensUnauthorized) String() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensUnauthorized ", 401)
}

func (o *ListPersonalAccessTokensUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListPersonalAccessTokensForbidden creates a ListPersonalAccessTokensForbidden with default headers values
func NewListPersonalAccessTokensForbidden() *ListPersonalAccessTokensForbidden {
	return &ListPersonalAccessTokensForbidden{}
}

/*
ListPersonalAccessTokensForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type ListPersonalAccessTokensForbidden struct {
	Payload *models.RestError
}

// IsSuccess returns true when this list personal access tokens forbidden response has a 2xx status code
func (o *ListPersonalAccessTokensForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list personal access tokens forbidden response has a 3xx status code
func (o *ListPersonalAccessTokensForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list personal access tokens forbidden response has a 4xx status code
func (o *ListPersonalAccessTokensForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this list personal access tokens forbidden response has a 5xx status code
func (o *ListPersonalAccessTokensForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this list personal access tokens forbidden response a status code equal to that given
func (o *ListPersonalAccessTokensForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *ListPersonalAccessTokensForbidden) Error() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensForbidden  %+v", 403, o.Payload)
}

func (o *ListPersonalAccessTokensForbidden) String() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensForbidden  %+v", 403, o.Payload)
}

func (o *ListPersonalAccessTokensForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListPersonalAccessTokensForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPersonalAccessTokensNotFound creates a ListPersonalAccessTokensNotFound with default headers values
func NewListPersonalAccessTokensNotFound() *ListPersonalAccessTokensNotFound {
	return &ListPersonalAccessTokensNotFound{}
}

/*
ListPersonalAccessTokensNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type ListPersonalAccessTokensNotFound struct {
	Payload *models.RestError
}

// IsSuccess returns true when this list personal access tokens not found response has a 2xx status code
func (o *ListPersonalAccessTokensNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list personal access tokens not found response has a 3xx status code
func (o *ListPersonalAccessTokensNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list personal access tokens not found response has a 4xx status code
func (o *ListPersonalAccessTokensNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list personal access tokens not found response has a 5xx status code
func (o *ListPersonalAccessTokensNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list personal access tokens not found response a status code equal to that given
func (o *ListPersonalAccessTokensNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListPersonalAccessTokensNotFound) Error() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensNotFound  %+v", 404, o.Payload)
}

func (o *ListPersonalAccessTokensNotFound) String() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensNotFound  %+v", 404, o.Payload)
}

func (o *ListPersonalAccessTokensNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListPersonalAccessTokensNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPersonalAccessTokensInternalServerError creates a ListPersonalAccessTokensInternalServerError with default headers values
func NewListPersonalAccessTokensInternalServerError() *ListPersonalAccessTokensInternalServerError {
	return &ListPersonalAccessTokensInternalServerError{}
}

/*
ListPersonalAccessTokensInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type ListPersonalAccessTokensInternalServerError struct {
	Payload *models.RestError
}

// IsSuccess returns true when this list personal access tokens internal server error response has a 2xx status code
func (o *ListPersonalAccessTokensInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list personal access tokens internal server error response has a 3xx status code
func (o *ListPersonalAccessTokensInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list personal access tokens internal server error response has a 4xx status code
func (o *ListPersonalAccessTokensInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list personal access tokens internal server error response has a 5xx status code
func (o *ListPersonalAccessTokensInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list personal access tokens internal server error response a status code equal to that given
func (o *ListPersonalAccessTokensInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *ListPersonalAccessTokensInternalServerError) Error() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensInternalServerError  %+v", 500, o.Payload)
}

func (o *ListPersonalAccessTokensInternalServerError) String() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensInternalServerError  %+v", 500, o.Payload)
}

func (o *ListPersonalAccessTokensInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *ListPersonalAccessTokensInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPersonalAccessTokensDefault creates a ListPersonalAccessTokensDefault with default headers values
func NewListPersonalAccessTokensDefault(code int) *ListPersonalAccessTokensDefault {
	return &ListPersonalAccessTokensDefault{
		_statusCode: code,
	}
}

/*
ListPersonalAccessTokensDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListPersonalAccessTokensDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the list personal access tokens default response
func (o *ListPersonalAccessTokensDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list personal access tokens default response has a 2xx status code
func (o *ListPersonalAccessTokensDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list personal access tokens default response has a 3xx status code
func (o *ListPersonalAccessTokensDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list personal access tokens default response has a 4xx status code
func (o *ListPersonalAccessTokensDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list personal access tokens default response has a 5xx status code
func (o *ListPersonalAccessTokensDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list personal access tokens default response a status code equal to that given
func (o *ListPersonalAccessTokensDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListPersonalAccessTokensDefault) Error() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] ListPersonalAccessTokens default  %+v", o._statusCode, o.Payload)
}

func (o *ListPersonalAccessTokensDefault) String() string {
	return fmt.Sprintf("[POST /auth/tokens][%d] ListPersonalAccessTokens default  %+v", o._statusCode, o.Payload)
}

func (o *ListPersonalAccessTokensDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ListPersonalAccessTokensDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
