// Code generated by go-swagger; DO NOT EDIT.

package enterprise_token_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// ListPersonalAccessTokensReader is a Reader for the ListPersonalAccessTokens structure.
type ListPersonalAccessTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPersonalAccessTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPersonalAccessTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListPersonalAccessTokensDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListPersonalAccessTokensOK creates a ListPersonalAccessTokensOK with default headers values
func NewListPersonalAccessTokensOK() *ListPersonalAccessTokensOK {
	return &ListPersonalAccessTokensOK{}
}

/*
ListPersonalAccessTokensOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListPersonalAccessTokensOK struct {
	Payload *models.AuthPatListResponse
}

// IsSuccess returns true when this list personal access tokens o k response has a 2xx status code
func (o *ListPersonalAccessTokensOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list personal access tokens o k response has a 3xx status code
func (o *ListPersonalAccessTokensOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list personal access tokens o k response has a 4xx status code
func (o *ListPersonalAccessTokensOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list personal access tokens o k response has a 5xx status code
func (o *ListPersonalAccessTokensOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list personal access tokens o k response a status code equal to that given
func (o *ListPersonalAccessTokensOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list personal access tokens o k response
func (o *ListPersonalAccessTokensOK) Code() int {
	return 200
}

func (o *ListPersonalAccessTokensOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensOK %s", 200, payload)
}

func (o *ListPersonalAccessTokensOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/tokens][%d] listPersonalAccessTokensOK %s", 200, payload)
}

func (o *ListPersonalAccessTokensOK) GetPayload() *models.AuthPatListResponse {
	return o.Payload
}

func (o *ListPersonalAccessTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthPatListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPersonalAccessTokensDefault creates a ListPersonalAccessTokensDefault with default headers values
func NewListPersonalAccessTokensDefault(code int) *ListPersonalAccessTokensDefault {
	return &ListPersonalAccessTokensDefault{
		_statusCode: code,
	}
}

/*
ListPersonalAccessTokensDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListPersonalAccessTokensDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this list personal access tokens default response has a 2xx status code
func (o *ListPersonalAccessTokensDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list personal access tokens default response has a 3xx status code
func (o *ListPersonalAccessTokensDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list personal access tokens default response has a 4xx status code
func (o *ListPersonalAccessTokensDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list personal access tokens default response has a 5xx status code
func (o *ListPersonalAccessTokensDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list personal access tokens default response a status code equal to that given
func (o *ListPersonalAccessTokensDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list personal access tokens default response
func (o *ListPersonalAccessTokensDefault) Code() int {
	return o._statusCode
}

func (o *ListPersonalAccessTokensDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/tokens][%d] ListPersonalAccessTokens default %s", o._statusCode, payload)
}

func (o *ListPersonalAccessTokensDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/tokens][%d] ListPersonalAccessTokens default %s", o._statusCode, payload)
}

func (o *ListPersonalAccessTokensDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ListPersonalAccessTokensDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
