// Code generated by go-swagger; DO NOT EDIT.

package enterprise_token_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pydio/cells-enterprise-sdk-go/models"
)

// RevokePersonalAccessTokenReader is a Reader for the RevokePersonalAccessToken structure.
type RevokePersonalAccessTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokePersonalAccessTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevokePersonalAccessTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRevokePersonalAccessTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRevokePersonalAccessTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRevokePersonalAccessTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokePersonalAccessTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRevokePersonalAccessTokenOK creates a RevokePersonalAccessTokenOK with default headers values
func NewRevokePersonalAccessTokenOK() *RevokePersonalAccessTokenOK {
	return &RevokePersonalAccessTokenOK{}
}

/* RevokePersonalAccessTokenOK describes a response with status code 200, with default header values.

RevokePersonalAccessTokenOK revoke personal access token o k
*/
type RevokePersonalAccessTokenOK struct {
	Payload *models.RestRevokeResponse
}

func (o *RevokePersonalAccessTokenOK) Error() string {
	return fmt.Sprintf("[DELETE /auth/tokens/{TokenId}][%d] revokePersonalAccessTokenOK  %+v", 200, o.Payload)
}
func (o *RevokePersonalAccessTokenOK) GetPayload() *models.RestRevokeResponse {
	return o.Payload
}

func (o *RevokePersonalAccessTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestRevokeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokePersonalAccessTokenUnauthorized creates a RevokePersonalAccessTokenUnauthorized with default headers values
func NewRevokePersonalAccessTokenUnauthorized() *RevokePersonalAccessTokenUnauthorized {
	return &RevokePersonalAccessTokenUnauthorized{}
}

/* RevokePersonalAccessTokenUnauthorized describes a response with status code 401, with default header values.

User is not authenticated
*/
type RevokePersonalAccessTokenUnauthorized struct {
}

func (o *RevokePersonalAccessTokenUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /auth/tokens/{TokenId}][%d] revokePersonalAccessTokenUnauthorized ", 401)
}

func (o *RevokePersonalAccessTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokePersonalAccessTokenForbidden creates a RevokePersonalAccessTokenForbidden with default headers values
func NewRevokePersonalAccessTokenForbidden() *RevokePersonalAccessTokenForbidden {
	return &RevokePersonalAccessTokenForbidden{}
}

/* RevokePersonalAccessTokenForbidden describes a response with status code 403, with default header values.

User has no permission to access this resource
*/
type RevokePersonalAccessTokenForbidden struct {
	Payload *models.RestError
}

func (o *RevokePersonalAccessTokenForbidden) Error() string {
	return fmt.Sprintf("[DELETE /auth/tokens/{TokenId}][%d] revokePersonalAccessTokenForbidden  %+v", 403, o.Payload)
}
func (o *RevokePersonalAccessTokenForbidden) GetPayload() *models.RestError {
	return o.Payload
}

func (o *RevokePersonalAccessTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokePersonalAccessTokenNotFound creates a RevokePersonalAccessTokenNotFound with default headers values
func NewRevokePersonalAccessTokenNotFound() *RevokePersonalAccessTokenNotFound {
	return &RevokePersonalAccessTokenNotFound{}
}

/* RevokePersonalAccessTokenNotFound describes a response with status code 404, with default header values.

Resource does not exist in the system
*/
type RevokePersonalAccessTokenNotFound struct {
	Payload *models.RestError
}

func (o *RevokePersonalAccessTokenNotFound) Error() string {
	return fmt.Sprintf("[DELETE /auth/tokens/{TokenId}][%d] revokePersonalAccessTokenNotFound  %+v", 404, o.Payload)
}
func (o *RevokePersonalAccessTokenNotFound) GetPayload() *models.RestError {
	return o.Payload
}

func (o *RevokePersonalAccessTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokePersonalAccessTokenInternalServerError creates a RevokePersonalAccessTokenInternalServerError with default headers values
func NewRevokePersonalAccessTokenInternalServerError() *RevokePersonalAccessTokenInternalServerError {
	return &RevokePersonalAccessTokenInternalServerError{}
}

/* RevokePersonalAccessTokenInternalServerError describes a response with status code 500, with default header values.

An internal error occurred in the backend
*/
type RevokePersonalAccessTokenInternalServerError struct {
	Payload *models.RestError
}

func (o *RevokePersonalAccessTokenInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /auth/tokens/{TokenId}][%d] revokePersonalAccessTokenInternalServerError  %+v", 500, o.Payload)
}
func (o *RevokePersonalAccessTokenInternalServerError) GetPayload() *models.RestError {
	return o.Payload
}

func (o *RevokePersonalAccessTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
