// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthOAuth2ConnectorLinkedinConfig auth o auth2 connector linkedin config
//
// swagger:model authOAuth2ConnectorLinkedinConfig
type AuthOAuth2ConnectorLinkedinConfig struct {

	// client ID
	ClientID string `json:"clientID,omitempty"`

	// client secret
	ClientSecret string `json:"clientSecret,omitempty"`

	// redirect URI
	RedirectURI string `json:"redirectURI,omitempty"`
}

// Validate validates this auth o auth2 connector linkedin config
func (m *AuthOAuth2ConnectorLinkedinConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth o auth2 connector linkedin config based on context it is used
func (m *AuthOAuth2ConnectorLinkedinConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthOAuth2ConnectorLinkedinConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthOAuth2ConnectorLinkedinConfig) UnmarshalBinary(b []byte) error {
	var res AuthOAuth2ConnectorLinkedinConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
