// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntConnector ent connector
//
// swagger:model entConnector
type EntConnector struct {

	// Id
	ID string `json:"Id,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// type
	Type string `json:"Type,omitempty"`
}

// Validate validates this ent connector
func (m *EntConnector) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ent connector based on context it is used
func (m *EntConnector) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntConnector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntConnector) UnmarshalBinary(b []byte) error {
	var res EntConnector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
