// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntDocTemplatePiece ent doc template piece
//
// swagger:model entDocTemplatePiece
type EntDocTemplatePiece struct {

	// context
	Context string `json:"Context,omitempty"`

	// long
	Long string `json:"Long,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// short
	Short string `json:"Short,omitempty"`
}

// Validate validates this ent doc template piece
func (m *EntDocTemplatePiece) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ent doc template piece based on context it is used
func (m *EntDocTemplatePiece) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntDocTemplatePiece) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntDocTemplatePiece) UnmarshalBinary(b []byte) error {
	var res EntDocTemplatePiece
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
