// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntExternalDirectoryTestResponse Test responses sends back arbitrary JSON contents
//
// swagger:model entExternalDirectoryTestResponse
type EntExternalDirectoryTestResponse struct {

	// directory response JSON
	DirectoryResponseJSON string `json:"DirectoryResponseJSON,omitempty"`

	// success
	Success bool `json:"Success,omitempty"`
}

// Validate validates this ent external directory test response
func (m *EntExternalDirectoryTestResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ent external directory test response based on context it is used
func (m *EntExternalDirectoryTestResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntExternalDirectoryTestResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntExternalDirectoryTestResponse) UnmarshalBinary(b []byte) error {
	var res EntExternalDirectoryTestResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
