// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntOAuth2ClientCollection ent o auth2 client collection
//
// swagger:model entOAuth2ClientCollection
type EntOAuth2ClientCollection struct {

	// static clients
	StaticClients []*AuthOAuth2ClientConfig `json:"staticClients"`
}

// Validate validates this ent o auth2 client collection
func (m *EntOAuth2ClientCollection) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStaticClients(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntOAuth2ClientCollection) validateStaticClients(formats strfmt.Registry) error {
	if swag.IsZero(m.StaticClients) { // not required
		return nil
	}

	for i := 0; i < len(m.StaticClients); i++ {
		if swag.IsZero(m.StaticClients[i]) { // not required
			continue
		}

		if m.StaticClients[i] != nil {
			if err := m.StaticClients[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("staticClients" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("staticClients" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this ent o auth2 client collection based on the context it is used
func (m *EntOAuth2ClientCollection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStaticClients(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntOAuth2ClientCollection) contextValidateStaticClients(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.StaticClients); i++ {

		if m.StaticClients[i] != nil {
			if err := m.StaticClients[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("staticClients" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("staticClients" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EntOAuth2ClientCollection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntOAuth2ClientCollection) UnmarshalBinary(b []byte) error {
	var res EntOAuth2ClientCollection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
