// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntDeleteJobVersionResponse ent delete job version response
//
// swagger:model entDeleteJobVersionResponse
type EntDeleteJobVersionResponse struct {

	// success
	Success bool `json:"Success,omitempty"`
}

// Validate validates this ent delete job version response
func (m *EntDeleteJobVersionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ent delete job version response based on context it is used
func (m *EntDeleteJobVersionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntDeleteJobVersionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntDeleteJobVersionResponse) UnmarshalBinary(b []byte) error {
	var res EntDeleteJobVersionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
