// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntListActionTemplatesRequest ent list action templates request
//
// swagger:model entListActionTemplatesRequest
type EntListActionTemplatesRequest struct {

	// all
	All bool `json:"All,omitempty"`
}

// Validate validates this ent list action templates request
func (m *EntListActionTemplatesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ent list action templates request based on context it is used
func (m *EntListActionTemplatesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EntListActionTemplatesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntListActionTemplatesRequest) UnmarshalBinary(b []byte) error {
	var res EntListActionTemplatesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
