// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EntDocTemplatesResponse ent doc templates response
//
// swagger:model entDocTemplatesResponse
type EntDocTemplatesResponse struct {

	// docs
	Docs []*EntDocTemplatePiece `json:"Docs"`

	// type
	Type string `json:"Type,omitempty"`
}

// Validate validates this ent doc templates response
func (m *EntDocTemplatesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDocs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntDocTemplatesResponse) validateDocs(formats strfmt.Registry) error {
	if swag.IsZero(m.Docs) { // not required
		return nil
	}

	for i := 0; i < len(m.Docs); i++ {
		if swag.IsZero(m.Docs[i]) { // not required
			continue
		}

		if m.Docs[i] != nil {
			if err := m.Docs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Docs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Docs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this ent doc templates response based on the context it is used
func (m *EntDocTemplatesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDocs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntDocTemplatesResponse) contextValidateDocs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Docs); i++ {

		if m.Docs[i] != nil {
			if err := m.Docs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Docs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Docs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EntDocTemplatesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntDocTemplatesResponse) UnmarshalBinary(b []byte) error {
	var res EntDocTemplatesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
