// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IpbanUnbanRequest ipban unban request
//
// swagger:model ipbanUnbanRequest
type IpbanUnbanRequest struct {

	// IP
	IP string `json:"IP,omitempty"`
}

// Validate validates this ipban unban request
func (m *IpbanUnbanRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ipban unban request based on context it is used
func (m *IpbanUnbanRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IpbanUnbanRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpbanUnbanRequest) UnmarshalBinary(b []byte) error {
	var res IpbanUnbanRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
