// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobsDeleteJobResponse jobs delete job response
//
// swagger:model jobsDeleteJobResponse
type JobsDeleteJobResponse struct {

	// delete count
	DeleteCount int32 `json:"DeleteCount,omitempty"`

	// success
	Success bool `json:"Success,omitempty"`
}

// Validate validates this jobs delete job response
func (m *JobsDeleteJobResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this jobs delete job response based on context it is used
func (m *JobsDeleteJobResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobsDeleteJobResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobsDeleteJobResponse) UnmarshalBinary(b []byte) error {
	var res JobsDeleteJobResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
