// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReportsListReportsResponse reports list reports response
//
// swagger:model reportsListReportsResponse
type ReportsListReportsResponse struct {

	// report dates
	ReportDates []int32 `json:"ReportDates"`
}

// Validate validates this reports list reports response
func (m *ReportsListReportsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this reports list reports response based on context it is used
func (m *ReportsListReportsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReportsListReportsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportsListReportsResponse) UnmarshalBinary(b []byte) error {
	var res ReportsListReportsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
